whatwg/fetch

- Overview.html
- Overview.src.html
This change introduces `body` property of Response class. Note that we don't
introduce `Request.body` at this moment and hence some properties and algorithms
defined in the Body mixin are moved to Request and Response.
`bodyUsed` property is now based on `IsDisturbed` defined in the streams spec.
Request.bodyUsed emulates the behavior without using streams.
> Introduce Response.body. (#118)

- Overview.html
- Overview.src.html
> Add an example using Response body

- Overview.html
- Overview.src.html
Content Security Policy has defined a set of integrations with Fetch
that make a little more sense than the hand-wavey "Whenever the
user agent requests a resource ..." descriptions in CSP1 and CSP2.
Finally.
This patch updates Fetch's placeholders to link to the new algorithms,
and adds a "policy list" attribute to response objects in order to
support those algorithms' requirements.
> Update Fetch with shiny, new CSP hooks

- Overview.html
- Overview.src.html
Let `req` be a Request with a non-null body. When constructing a new Request
from it, it should be marked as disturbed so as not to confuse users. As a
Request with the null body cannot be disturbed, this change sets `req`'s body
to an empty byte stream.
This was discussed at #61. It is not yet decided whether we make it possible to disturb a Request with the null body or setting the body to a non-null stream in such cases, but they are indistinguishable until we expose Request.prototype.body. See https://github.com/yutakahirano/fetch-with-streams/issues/60.
> Mark passed Request object as disturbed

- Overview.html
- Overview.src.html
This mostly affects the way stylesheets work in service workers. See
https://github.com/slightlyoff/ServiceWorker/issues/757 for details.
> Use the URL from the response, if it has one

- Overview.html
- Overview.src.html
We need to do CSP reporting before we do any upgrades or mixed content checks.
This patch adjusts Main Fetch accordingly.
> Separate 'report-only' and 'enforce' CSP execution

- Overview.src.html
`res.headers.get("content-type")` could be `null` or `Application/json; Charset=utf-8`
> improve example

- Overview.html
- Overview.src.html
This change fixes the type of Response.prototype.body.
- It should not be [SameObject] as clone() will change the attribute.
- It should be nullable.
> Fix Response body IDL

- Overview.html
- Overview.src.html
See https://github.com/whatwg/html/issues/461 for context. This allows
HTML to invoke a single algorithm to “handle redirects”, a concept it
mentions but does not actually define.
This changes the processing rules for redirect mode “manual”, but since
that is a rather new feature that should be fine.
> Introduce HTTP-redirect fetch

- Overview.html
- Overview.src.html
This change replaces byte streams used in request and response with ReadableStream. This change
also unifies some properties and operations which was defined separately in Request and Response
classes.
The change is based on
https://github.com/yutakahirano/fetch-with-streams/blob/master/body-readable-stream.md.
Depending specs need to be changed as well.
> Replace byte stream with ReadableStream.

- Overview.html
- Overview.src.html
Fetch's current language around cookies is fairly vague. I think we can
do a little better, even without changing the Cookie specification.
> Clarify the hooks into RFC6265

- Overview.html
- Overview.src.html
> Define the WebSocket client handshake in terms of Fetch

- Overview.html
- Overview.src.html
This will enable CSP to correctly handle nonce checks during Fetch, which
it fails to do today. We'll need to make some changes to HTML to support
this new mechanism, but that will come in a separate patch.
> Issue #269: Add 'cryptographic nonce metadata' to requests.

- Overview.html
- Overview.src.html
With this change request's referrer policy is updated before calculating referrer so that the referrer policy actually used for the referrer calculation is transferred to the service worker and the default referrer policy is not transferred to the service worker.
This change fixes #266.
> Update request's referrer policy when fetching

- Overview.html
- Overview.src.html
This is in support of the 'unsafe-dynamic' source expression in
CSP3: https://w3c.github.io/webappsec-csp/#unsafe-dynamic-usage.
w3c/webappsec-csp#70
> Add 'parser metadata' to requests.

- Overview.html
- Overview.src.html
This change enables constructing a Response from ReadableStream, as discussed in
https://github.com/yutakahirano/fetch-with-streams/issues/63.
> Response construction with ReadableStream

- Overview.html
- Overview.src.html
Fixes #159. The difference with the previous attempt is that it now has
a “same-origin” mode restriction (enforced through the Fetch API).
> Add "only-if-cached" cache mode back

- Overview.html
- Overview.src.html
> More wildcards in CORS when used without credentials

- Overview.html
- Overview.src.html
In #146 I tried to let service worker responses that were not synthetic
to keep their url list. However, the way I fixed that regressed url
lists for a number of responses: HTTP cache responses, about URL
responses, etc.
This fix instead tries to keep the old setup and only overwrites the
url list of a response if it’s empty.
Fixes #312.
> Make sure all responses have a URL list

- Overview.html
- Overview.src.html
This change adds some ReadableStream operations that are used in https://github.com/slightlyoff/ServiceWorker/pull/934.
> Add ReadableStreamOperations for ServiceWorker

- Overview.html
- Overview.src.html
Trailer support we can add in the future if this minimal viable
solution is a success:
* Support for synthetic responses.
* Support for (synthetic) requests.
* Trailer headers that have semantics.
Fixes #343 and fixes #34.
> Add trailer support to network responses

- Overview.html
- Overview.src.html
This change fixes ReadableStream abstract operation markup and names. Fixes #361.
> Fix ReadableStream operations

- Overview.html
- Overview.src.html
HTML gives data URLs a unique origin when navigating to them to prevent
a class of XSS attacks.
Since browsers already largely allow data URLs in all other contexts
this commit aligns with that, opting them into being same-origin
elsewhere.
Workers however are still prevented. It would create problems for
shared workers and potentially also for dedicated workers.
Fixes #381.
> Treat data URLs as same-origin, except for workers

- Overview.html
- Overview.src.html
Folks are using the Request constructor in unexpected ways and
therefore it is throwing in unexpected ways (in particular when mode is
“navigate” or when setting referrer to a cross-origin URL). This will
make it throw less, while not really being less useful.
Fixes #245.
> Make Request constructor more forgiving

- Overview.html
- Overview.src.html
Related discussion in https://github.com/w3c/beacon/pull/27. 
@annevk ptal, is this on the right track? I have a few ???'s and TODO's that I could use help with :)
> allow Request to outlive environment settings object

- Overview.html
- Overview.src.html
Add request's reserved client and target client id
This patch defines the request's reserved client and the target client
id. The reserved client of a request is set to an environment or an
environment settings object during a navigation or a worker creation
request, respectively. The target client id of a request is set to the
target browsing context's active document's environment settings
object's id during a navigation. The given values are primarily used
to provide the reserved client's id and target client's id to service
workers' fetch event handlers.
This removes the request's target browsing context as the reserved
client provides the same information.
Related issue: https://github.com/w3c/ServiceWorker/issues/870
Related change: https://github.com/whatwg/html/pull/1776
> Add request's reserved client and target client id

- fetch.bs
- fetch.html
RFC 2388 has been obsoleted by RFC 7578. This change reflects a similar
change applied to the HTML spec.
See https://github.com/whatwg/html/issues/398 for discussion.
> Reference RFC 7578 instead of RFC 2388

- fetch.bs
Section 4.2.6., 1st example, last para:
bar.com -> bar.invalid
> Update fetch.bs: bar.com should be bar.invalid

- fetch.bs
Since Headers has an iterator now through its iterable<> declaration
there’s no real need to special case.
It might be slightly faster to have it there, but this is not
performance-critical code and I’d rather have it be simple.
> Simplify HeadersInit

- .travis.yml
Travis needs Java8 to run the `vnu.jar` HTML checker. This change causes Travis to use the full path to the `java` binary, to ensure it always gets the right (Java8) one.
> Meta: Give Travis the full path to the java binary

- fetch.bs
Instead use the CORS flag and request’s method as indicators for when
to include it.
Fixes #225.
> Remove request's omit-Origin-header flag

- fetch.bs
For “image” it was not web-compatible and checking the others doesn’t
seem worth it given there are no known issues with sniffing there.
Closes #395.
> Only use nosniff for "script" and "style"

- fetch.bs
Once we planned to have both ReadableStream and ReadableByteStream and wrote a note in the spec for a possible naming change in the future. But the plan was abandoned and we only have ReadableStream. Let's remove the obsolete note.
> Remove an obsolete note for ReadableStream type

- fetch.bs
Commit eb89fcd5 ("Remove request's omit-Origin-header flag") changed the
phrasing in section 3.1, but is missing a word in the note about the Origin
header.
> Add a missing "is" to 3.1 ("Origin header").

- fetch.bs
...and replace "read a request" with it.
Fixing #441.
> Specify "upload body of a request"

- fetch.bs
This change enables developers to create a request from a ReadableStream body. fetch() reads data from the body and sends it to the server.
Fixing https://github.com/yutakahirano/fetch-with-streams/issues/66.
> Uploading a Request made from a ReadableStream body

- fetch.bs
HTTP is taking too long to sort this out.
Tests: https://github.com/w3c/web-platform-tests/pull/4525.
Fixes #332.
> Define header value inline

- fetch.bs
This is how it's used to be and what the Fetch Standard says now is causing subtle issues on servers.
> Only set Access-Control-Request-Headers when its value is non-empty

- fetch.bs
As Request.body is exposed, we need to specify how to handle the body property of the input Request more correctly. After
```
let r = new Request(request, ...);
```
successfully returns,
- `request.body` should remain unchanged.
- `request.bodyUsed` should be true.
Fixing https://github.com/yutakahirano/fetch-with-streams/issues/60.
> Fix body handling on the Request constructor

- fetch.bs
Origins should be compared as being same-origin in the main fetch algorithm.
Fixes #468.
> Clarified that origins are compared as being same-origin

- fetch.bs
This fixes #303. I don't think there's anything else to do with this PR, but I need to make changes to SW to set this flag on particular APIs.
> Changing skip-service-worker flag to use-service-workers enum

- fetch.bs
Usage of the 'ftp:' protocol when requesting subresources from non-'ftp:'
clients has slowly declined over the last few years to the point where
it represents a [negligable amount of traffic][1]. The protocol does not
support modern requirements, like encryption, and there's interest from
at least one browser vendor in [removing support for FTP from their
network stack entirely][2].
To that end, this patch alters Fetch to block FTP subresources from
webby clients. That is, a page delivered from `http://example.com/`
will receive a network error response to requests like those generated
from `<img src='ftp://example.com/image.png'>`.
[1]: https://www.chromestatus.com/metrics/feature/timeline/popularity/531
[2]: https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/bIJdwwoQ98U/-F1aL …
> Block 'ftp:' requests from non-'ftp:' clients.

- fetch.bs
Instead compare header names using a byte-case-insensitive match and
lowercase them when exposed through the API.
Fixes #203 and fixes #304.
> Stop lowercasing header names

- fetch.bs
We now have two separate algorithms that can be used rather than one
with type confusion:
* “extracting header values” (takes a header)
* “extracting header list values” (takes a name and a header list)
Fixes #474.
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/annevk/value-extraction/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/ff8a3e9..annevk/value-extraction:a9d8f59.html)
> Breaking: redo value parsing as value extraction

- fetch.bs
Requests with keepalive flag set are allowed to outlive the environment
settings object. We want to make sure that such requests do not
negatively impact the user experience when a page is unloaded, etc.
This limits the amount of (body) bytes that can be inflight at any point
when the request has the keepalive flag set; this flag is set by
sendBeacon.
Background: https://github.com/w3c/beacon/pull/39
***
[Preview](https://s3.amazonaws.com/pr-preview/igrigorik/fetch/master.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/68a9867..igrigorik:master:1bd7e76.html)
> Enforce limit on inflight keepalive bytes

- fetch.bs
Since an attribute that returns a promise can be made to return a
rejecting promise as well. (We really need [Cached] or some such.)
Tests: https://github.com/w3c/web-platform-tests/issues/4811.
> Response's trailer cannot use [SameObject]

- fetch.bs
As [discussed](http://logs.glob.uno/?c=freenode%23whatwg&s=16+Dec+2016&e=30+Dec+2016#c1014610) on IRC:
* `video`, `audio` and `track` types are currently a single destination: `media`
* This is because we agreed on that as part of https://github.com/whatwg/fetch/pull/211
* I agreed to this change, saying "Merging `track` into `media` is probably also possible."
* It is not. (Not in a clean way, anyway)
* `track` is quite different from `audio`/`video` and is represented internally inside Blink using a different resource type and performs different `type` checks
* @annevk prefers that if we split `track` from `media`, we'd split them all to 3 different destinations, which will enable audio/video specific `Accept` headers.
* destination is also used (and exposed) in SW, but according to …
> Split up media into video, audio and track

- fetch.bs
Instead of just 0x2C, use 0x2C 0x20 somewhat consistently (except where we can't and point it out) as that is what XMLHttpRequest implementations have always done and nobody likes too much change.
Fixes the Fetch part of https://github.com/whatwg/xhr/issues/108 and https://github.com/whatwg/xhr/issues/109.
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/annevk/combine/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/89f7361...e3978ef.html)
> Change combine and combined value to use 0x2C 0x20 

- fetch.bs
Depends on https://github.com/whatwg/infra/pull/76.
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/annevk/infra-byte-case-insensitive/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/04968e2...4ad2be6.html)
> Editorial: let Infra define byte-case-insensitive

- fetch.bs
Also keep “includes credentials” steps next to each other by moving
another step and update origin terminology.
Fixes https://github.com/whatwg/html/issues/2396.
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/annevk/http-redirect-fetch/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/3b4cb54...c958914.html)
> Do not always set the recursive flag in HTTP-redirect fetch

- fetch.bs
Fixes #386.
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/annevk/internal-response/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/b59c72b...36bfd7b.html)
> Editorial: clarify that an internal response cannot be filtered

- fetch.bs
Fixes part of https://github.com/whatwg/url/issues/241.
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/annevk/url-terminology/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/869ec2c...c985104.html)
> Move some terminology from the URL Standard here

- fetch.bs
For #373.
Also should help #336 (since HTTP clearly says this, and there's a direct reference now).
I think it addresses #307 (although Anne may want a different approach).
Touches #144.
***
[Preview](https://s3.amazonaws.com/pr-preview/mnot/fetch/http-cache.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/3b4cb54...mnot:edef79f.html)
> Http cache

- fetch.bs
***
[Preview](https://s3.amazonaws.com/pr-preview/nox/fetch/websocket-origin.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/cbca2c2...nox:c43ea5c.html)
> Properly set the Origin header for WebSocket requests

- fetch.bs
Commit 5869c43a27fff06c6dfc228fe1288018f7f2168d started describing the steps
to append to a header list with an ordered list but never added a closing
`</ol>` tag, which meant the entire rest of the contents were wrongly indented
and considered part of those steps.
***
[Preview](https://s3.amazonaws.com/pr-preview/rakuco/fetch/close-ol-tag-headerlist-append.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/406c5a6...rakuco:3787352.html)
> Meta: Close <ol> tag in concept-header-list-append.

- fetch.bs
With this change the "transmit body" algorithm queues "process request body" tasks so that the client can notice the body transmission progress.
Fixes #495.
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/process-request/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/9289687...f523b19.html)
> Queue "process request body" tasks during request body transmission

- fetch.bs
As it relates to the fetching algorithm, the term "basic" is sub-optimal
for a number of reasons:
- It implies a relative level of simplicity. Because the algorithm
includes an invocation of HTTP Fetch, it is conceptually more complex
than most other fetching algorithms defined in the specification.
- It suggests a relationship to the "basic" request tainting value and
"basic" filtered response. While the algorithm is invoked for requests
whose tainting is "basic", it is also invoked for requests whose
tainting is set to "opaque".
Re-name the algorithm to "scheme fetch" in order to more precisely
describe its behavior while avoiding association with any particular
request tainting value.
---
@annevk I'm probably only thinking along these lines because of my inexperience
with the …
> Editorial: rename "basic fetch" to "scheme fetch"

- fetch.bs
See https://lists.w3.org/Archives/Public/public-webappsec/2017May/0022.html
***
[Preview](https://s3.amazonaws.com/pr-preview/devd/fetch/patch-1.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/92228c4...devd:ebcdd85.html)
> Remove null origin issue

- fetch.bs
Add a potential destination definition and processing, to enable preload
processing to decouple the `as` value from `destination` to enable
preloading the empty destination using the `fetch` keyword.
This is an alternative solution to https://github.com/whatwg/fetch/pull/442 as discussed in https://github.com/whatwg/fetch/pull/442#discussion_r103624566
***
[Preview](https://s3.amazonaws.com/pr-preview/yoavweiss/fetch/potential_destination.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/a38ae96...yoavweiss:ad27990.html)
> Add potential destination.

- fetch.bs
This completes https://github.com/whatwg/fetch/pull/547 and makes sure that the potential destination is not the empty string.
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/potential_destination_not_empty_string/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/d6266c7...c33b1fd.html)
> Make sure that potential destination is not the empty string

- fetch.bs
See https://stackoverflow.com/a/45081016/441757
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/sideshowbarker/vary-for-all-responses/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/f3bb219...6d74cb5.html)
> Advise `Vary` even for non-CORS-request responses

- fetch.bs
The operation takes a reader but we passed a stream. This change fixes that.
Fixes #570.
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/reading-a-chunk/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/194c2a1...6aad002.html)
> Use "read a chunk" operation correctly

- fetch.bs
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/editorial-headers/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/c5a1394...032184d.html)
> Editorial: Making headers their own property

- fetch.bs
We already have this in the XHR spec, but I think it would be helpful to
readers to also have a note in the Fetch spec at point of use, because the
Fetch spec is what gets cited at StackOverflow and such as the source for
requirements on what causes a preflight. So omitting mention of this case from
the Fetch spec risks making people (continue to) forget this is among the
things that could be causing a preflight they’re running into but that they
don’t understand the reason for or how to prevent it.
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/sideshowbarker/event-listeners-and-preflight/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/07999e9...7bfea5c.html)
> Editorial: add note on event listeners & preflight

- fetch.bs
This was made possible due to ba175cf1100045da83ed0d7768629653aa979c20 making type a subset.
Fixes #581.
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/annevk/remove-request-type/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/8a91018...25437fe.html)
> Fold request type into destination

- fetch.bs
This exception also broke simple service worker passthrough handling.
Tests: ...
Fixes #583.
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/annevk/no-cors-integrity/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/8a91018...334d67a.html)
> Using integrity with "no-cors" is fine same-origin

- fetch.bs
In particular, now the fill algorithm no longer takes Headers objects,
the Request constructor algorithm will need to deal with that situation
itself.
Regressed in 00fce0d96e799f5bc8bc53b30fcec56c4e0b948c.
(Also fix some minor linking issues Bikeshed found.)
Fixes #483.
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/annevk/regression-fix/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/686a1ad...d91f5df.html)
> Regression: make Request constructor account for changes to fill

- fetch.bs
Fixes part of https://github.com/w3c/ServiceWorker/issues/1188.
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/annevk/foreign-fetch/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/9fa071b...2ff1550.html)
> Remove "foreign" service-workers mode

- fetch.bs
Fixes #558.
This probably does not matter as it's never going to be same-origin, but better safe than sorry.
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/annevk/preflight-service-workers-mode/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/bc23529...7830c74.html)
> CORS preflights need a service-workers mode of "none"

- fetch.bs
One day this will be complete and I will retire.
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/cancelation/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/a4290d1...8e1d2d5.html)
> Aborting fetch

- fetch.bs
Fixes #613.
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/annevk/references/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/d095af0...0d1bede.html)
> Reference correct WebSocket protocol RFC

- fetch.bs
Fixes #612.
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/sideshowbarker/credentials-clarification/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/34027b6...80231d2.html)
> Clarify that credentials include HTTP auth

- fetch.bs
This PR is a WIP, and does not yet contain information about the members of Request objects that are available as a result of implementing the Body interface. I just wanted to push this up before it is finished to get some feedback so I could start working on any requested changes while I work on finishing it.
Was a little unsure as to how vague I should be in the descriptions below, so any feedback on this to fix or clarify would be appreciated. Thanks!
This satisfies part of https://github.com/whatwg/fetch/issues/543
***
[Preview](https://s3.amazonaws.com/pr-preview/domfarolino/fetch/request-domintro.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/d84658e...domfarolino:9139ab5.html)
> [WIP] Request domintro box

- fetch.bs
These two are the ones which are being implemented, so starting with
them for now.
***
[Preview](https://s3.amazonaws.com/pr-preview/bfgeek/fetch/master.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/e5abf0f...bfgeek:89a8f25.html)
> Adds "audioworklet" and "paintworklet" as destinations.

- fetch.bs
Fixes #630.
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/annevk/ws-no-referrer/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/8ab040a...46984f2.html)
> WebSocket handshake has no referrer

- fetch.bs
As discussed in https://github.com/whatwg/fetch/issues/567, browsers have
allowed various cross-origin requests with non-safelisted Content-Type header
values to be sent without CORS preflights. These have occurred either by
accident (and now can't be reversed for compatibility reasons) or because of
design constraints (requests that are implemented outside of the web platform
layer). These CORS exceptions are believed to be safe, but the spec should
document them so that servers know to expect them.
I've added a note about the Content-Type exceptions, but haven't added them to
the safelist, because doing so would imply that web content can trigger
requests with these Content-Type headers and arbitrary bodies. We don't want to
allow fully attacker-controlled requests with these headers, …
> Document CORS safelist exceptions

- fetch.bs
Checking if body is not done had a problem in that if body's stream is null it would end up not working as "done" tries to read internal slots from a body's stream.
This also makes the language around RST_STREAM frames consistent.
Fixes #635.
***
<a href="https://fetch.spec.whatwg.org/branch-snapshots/annevk/body-stream-can-be-null/" title="Last updated on Nov 24, 2017, 11:12 AM GMT">Preview</a> | <a href="https://s3.amazonaws.com/pr-preview/whatwg/fetch/f8a6a5d...e6e3228.html" title="Last updated on Nov 24, 2017, 11:12 AM GMT">Diff</a>
> More eargerly send RST_STREAM on redirects

- fetch.bs
WebIDL recently introduced dedicated syntax for mixins[1]. So, we can
replace `[NoInterfaceObject]` and `implements` with `interface mixin` and
`includes`.
This following interface is impacted by this change:
- Body
This fixes #624 issue.
Test: https://github.com/w3c/web-platform-tests/pull/8701
[1] https://github.com/heycam/webidl/commit/45e8173d40ddff8dcf81697326e094bcf8b92920
***
<a href="https://whatpr.org/fetch/645.html" title="Last updated on Dec 18, 2017, 3:15 PM GMT (dab71e0)">Preview</a> | <a href="https://whatpr.org/fetch/645/fd28675...dab71e0.html" title="Last updated on Dec 18, 2017, 3:15 PM GMT (dab71e0)">Diff</a>
> Use `interface mixins` instead of `[NoInterfaceObject]`

- fetch.bs
This PR adds the RequestInit members to the Request domintro box. I wasn't sure if I should be linking to the enums for things like RequestInit.{mode, credentials, etc} to make it easy for people to see the actual valid values of objects or not, so if that is necessary I'll adjust this for sure.
There are also a couple misc wording fixes I made for the lower content I added in an earlier PR.
Makes progress on https://github.com/whatwg/fetch/issues/543
***
<a href="https://whatpr.org/fetch/620.html" title="Last updated on Jan 13, 2018, 12:36 PM GMT (0e4a7be)">Preview</a> | <a href="https://whatpr.org/fetch/620/fd28675...0e4a7be.html" title="Last updated on Jan 13, 2018, 12:36 PM GMT (0e4a7be)">Diff</a>
> Add RequestInit members to Request domintro

- fetch.bs
Handles cases where the signal's aborted flag is already set.
***
<a href="https://whatpr.org/fetch/670.html" title="Last updated on Feb 12, 2018, 8:41 AM GMT (1a4c685)">Preview</a> | <a href="https://whatpr.org/fetch/670/36ef3c8...1a4c685.html" title="Last updated on Feb 12, 2018, 8:41 AM GMT (1a4c685)">Diff</a>
> Following signals. Fixes #668.

- fetch.bs
Currently, the following code snippet replaces `request`'s body as one would expect:
```javascript
let request = new Request(url, { method: "POST", body: "foo" })
request = new Request(request, { body: "bar" })
```
But this snippet throws a TypeError early in Request's constructor:
```javascript
let request = new Request(url, { method: "POST", body: "foo" })
await request.text()  // disturb the body
request = new Request(request, { body: "bar" })  // throws
```
This commit's changes allows the latter code snippet to work like the first one.
Fixes #674.
***
<a href="https://whatpr.org/fetch/675.html" title="Last updated on Mar 15, 2018, 8:10 AM GMT (03a8ac0)">Preview</a> | <a href="https://whatpr.org/fetch/675/ae71682...03a8ac0.html" title="Last updated on Mar 15, 2018, 8:10 AM GMT …
> Allow used body replacement in Request constructor

- fetch.bs
Fixes #364.
***
<a href="https://whatpr.org/fetch/701.html" title="Last updated on Apr 17, 2018, 11:01 AM GMT (9bb9f09)">Preview</a> | <a href="https://whatpr.org/fetch/701/5b7dae0...9bb9f09.html" title="Last updated on Apr 17, 2018, 11:01 AM GMT (9bb9f09)">Diff</a>
> Set response's CSP list once

- fetch.bs
The reason this works is that https://html.spec.whatwg.org/#concept-media-load-resource (HTML's media element fetching algorithm) special cases MediaSource and MediaStream and handles them way before Fetch is hit.
Tests: ...
Fixes #457.
***
<a href="https://whatpr.org/fetch/708.html" title="Last updated on Apr 18, 2018, 11:52 AM GMT (0374f9e)">Preview</a> | <a href="https://whatpr.org/fetch/708/fd8ee5c...0374f9e.html" title="Last updated on Apr 18, 2018, 11:52 AM GMT (0374f9e)">Diff</a>
> Only allow blob: URLs that point to Blob objects

- fetch.bs
Most features in the platform have this default and not having this default causes multiple connections in contemporary implementations. It also causes confusion as switching from XMLHttpRequest to fetch() is not as seamless as it could be.
Making this change will also make it easier for <script type=module> to have this default as per discussion in https://github.com/whatwg/html/issues/2557.
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/annevk/fetch-api-credentials-mode/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/8a91018...5550bf9.html)
> Make fetch() use "same-origin" credentials by default

- fetch.bs
Service workers needs it.
Fixes #376.
***
<a href="https://whatpr.org/fetch/705.html" title="Last updated on Apr 17, 2018, 3:49 PM GMT (b98a5d8)">Preview</a> | <a href="https://whatpr.org/fetch/705/860922f...b98a5d8.html" title="Last updated on Apr 17, 2018, 3:49 PM GMT (b98a5d8)">Diff</a>
> Add response's cache state back

- fetch.bs
Commit message nit: Fixes #711.
***
<a href="https://whatpr.org/fetch/713.html" title="Last updated on Apr 19, 2018, 2:14 PM GMT (fb9204b)">Preview</a> | <a href="https://whatpr.org/fetch/713/8193ffe...fb9204b.html" title="Last updated on Apr 19, 2018, 2:14 PM GMT (fb9204b)">Diff</a>
> Editorial: use Infra to define header list

- fetch.bs
Closes #658
***
<a href="https://whatpr.org/fetch/659.html" title="Last updated on Jan 15, 2018, 12:09 PM GMT (1450e14)">Preview</a> | <a href="https://whatpr.org/fetch/659/b21fdeb...1450e14.html" title="Last updated on Jan 15, 2018, 12:09 PM GMT (1450e14)">Diff</a>
> Add a `prefetch` initiator

- fetch.bs
...and so extensions should use [`partial interface mixin`](https://heycam.github.io/webidl/#partial-interface-mixin) rather than `interface mixin`.
See also https://github.com/whatwg/html/pull/3650
***
<a href="https://whatpr.org/fetch-1/719.html" title="Last updated on Apr 27, 2018, 10:43 AM GMT (4b3690b)">Preview</a> | <a href="https://whatpr.org/fetch/719/d5d0840...4b3690b.html" title="Last updated on Apr 27, 2018, 10:43 AM GMT (4b3690b)">Diff</a>
> WindowOrWorkerGlobalScope is a mixin

- fetch.bs
***
<a href="https://whatpr.org/fetch/734.html" title="Last updated on May 24, 2018, 10:45 AM GMT (9479f7c)">Preview</a> | <a href="https://whatpr.org/fetch/734/794dd54...9479f7c.html" title="Last updated on May 24, 2018, 10:45 AM GMT (9479f7c)">Diff</a>
> Editorial: avoid normative keywords in domintro block

- fetch.bs
Otherwise things go wrong for "no-cors" POST redirects.
Fixes #593.
***
<a href="https://whatpr.org/fetch/594.html" title="Last updated on May 24, 2018, 12:10 PM GMT (398ce19)">Preview</a> | <a href="https://whatpr.org/fetch/594/794dd54...398ce19.html" title="Last updated on May 24, 2018, 12:10 PM GMT (398ce19)">Diff</a>
> Avoid using the CORS flag to reset request's origin in redirects

- fetch.bs
This is a refactoring change.
Fixes #732.
***
<a href="https://whatpr.org/fetch/739.html" title="Last updated on May 28, 2018, 10:08 AM GMT (de45648)">Preview</a> | <a href="https://whatpr.org/fetch/739/af45ce3...de45648.html" title="Last updated on May 28, 2018, 10:08 AM GMT (de45648)">Diff</a>
> Move definition of "reload-navigation flag"

- fetch.bs
This is part of #144.
The aim is to allow APIs to use the range header for no-cors requests, and allow them to pass through a service worker, but disallow modification of these requests, and disallow developers creating their own no-cors ranged requests.
***
<a href="https://whatpr.org/fetch/560.html" title="Last updated on May 29, 2018, 11:31 AM GMT (e1ad29d)">Preview</a> | <a href="https://whatpr.org/fetch/560/bd9b4e3...e1ad29d.html" title="Last updated on May 29, 2018, 11:31 AM GMT (e1ad29d)">Diff</a>
> Allow range header to be set by APIs

- fetch.bs
This more clearly indicates the input is (supposed to be) ASCII safe.
***
<a href="https://whatpr.org/fetch/742.html" title="Last updated on May 28, 2018, 12:03 PM GMT (60f3384)">Preview</a> | <a href="https://whatpr.org/fetch/742/efe088f...60f3384.html" title="Last updated on May 28, 2018, 12:03 PM GMT (60f3384)">Diff</a>
> Editorial: replace UTF-8 encode with isomorphic encode

- fetch.bs
I used [this horrible piece of code](https://gist.github.com/jakearchibald/ceb666e0a9271b55cd48d07dac2b74b6) (run in the console) to identify variables that weren't correctly defined.
***
<a href="https://whatpr.org/fetch/749.html" title="Last updated on May 30, 2018, 2:48 PM GMT (8ce0a4c)">Preview</a> | <a href="https://whatpr.org/fetch/749/ffbaefb...8ce0a4c.html" title="Last updated on May 30, 2018, 2:48 PM GMT (8ce0a4c)">Diff</a>
> Fixing variable definitions and scoping. Fixes #706.

- fetch.bs
Also remove some obsolete comments.
Fixes #694.
***
<a href="https://whatpr.org/fetch/738.html" title="Last updated on May 30, 2018, 1:40 PM GMT (fbcaa6f)">Preview</a> | <a href="https://whatpr.org/fetch/738/78a8dcd...fbcaa6f.html" title="Last updated on May 30, 2018, 1:40 PM GMT (fbcaa6f)">Diff</a>
> Block AFP ports (427, 548)

- fetch.bs
I hadn't really appreciated this with the initial PR, but preventing encoding solves a pretty big gotcha if developers tried to fetch ranges with `fetch()`.
***
<a href="https://whatpr.org/fetch/764.html" title="Last updated on Jun 14, 2018, 12:54 PM GMT (571aa0f)">Preview</a> | <a href="https://whatpr.org/fetch/764/2f3d04d...571aa0f.html" title="Last updated on Jun 14, 2018, 12:54 PM GMT (571aa0f)">Diff</a>
> Additional reasoning for sending Accept-Encoding: identity

- fetch.bs
Remove the warning that HTTP authentication is prohibited for
WebSockets.
See #565 for background.
***
<a href="https://whatpr.org/fetch/761.html" title="Last updated on Jun 15, 2018, 2:21 PM GMT (21e683d)">Preview</a> | <a href="https://whatpr.org/fetch/761/2f3d04d...21e683d.html" title="Last updated on Jun 15, 2018, 2:21 PM GMT (21e683d)">Diff</a>
> Stop saying WebSocket auth is disallowed

- fetch.bs
This header makes it easier for sites to block unwanted "no-cors" cross-origin requests.
Tests: ...
Fixes #687.
***
<a href="https://whatpr.org/fetch/733.html" title="Last updated on Jun 18, 2018, 12:20 PM GMT (ed96a17)">Preview</a> | <a href="https://whatpr.org/fetch/733/2f3d04d...ed96a17.html" title="Last updated on Jun 18, 2018, 12:20 PM GMT (ed96a17)">Diff</a>
> Define Cross-Origin-Resource-Policy response header

- fetch.bs
Fixes #345.
***
<a href="https://whatpr.org/fetch/714.html" title="Last updated on Apr 19, 2018, 2:25 PM GMT (5b89338)">Preview</a> | <a href="https://whatpr.org/fetch/714/8193ffe...5b89338.html" title="Last updated on Apr 19, 2018, 2:25 PM GMT (5b89338)">Diff</a>
> Clarify how Headers does not support Set-Cookie

- fetch.bs
As of w3c/reporting#41, the Reporting spec sends CORS preflights for report uploads if the origin of the collector is different than the origin of the reports in the upload.  That means we can remove Reporting from the CORS protocol exception list.
***
<a href="https://whatpr.org/fetch/776.html" title="Last updated on Jul 9, 2018, 1:17 PM GMT (61605e1)">Preview</a> | <a href="https://whatpr.org/fetch/776/e6cbef2...61605e1.html" title="Last updated on Jul 9, 2018, 1:17 PM GMT (61605e1)">Diff</a>
> Remove Reporting API from CORS exceptions

- fetch.bs
It could be that this should call https://streams.spec.whatwg.org/#create-readable-stream or https://streams.spec.whatwg.org/#create-readable-byte-stream (#267?) instead of trying to go through the `ReadableStream()` constructor, with all the ambiguity about how modifying `Object`'s prototype should affect things.
@domenic
***
<a href="https://whatpr.org/fetch/781.html" title="Last updated on Aug 9, 2018, 1:25 PM GMT (f514b21)">Preview</a> | <a href="https://whatpr.org/fetch/781/b3492ec...f514b21.html" title="Last updated on Aug 9, 2018, 1:25 PM GMT (f514b21)">Diff</a>
> Be clearer about how Fetch creates ReadableStreams.

- fetch.bs
H2 priorities are lost when passing through a service worker. https://medium.baqend.com/chromes-service-workers-break-http-2-priorities-649c4e0fa930
Although priorities are hand-wavy right now, it seems right to copy them from one request to another.
***
<a href="https://whatpr.org/fetch/785.html" title="Last updated on Aug 15, 2018, 3:06 PM GMT (f477930)">Preview</a> | <a href="https://whatpr.org/fetch/785/28f06ba...f477930.html" title="Last updated on Aug 15, 2018, 3:06 PM GMT (f477930)">Diff</a>
> Copy priority so service worker pass-through requests don't lose it

- fetch.bs
This grounds it a bit more in an Infra data structure.
Fixes #735.
***
<a href="https://whatpr.org/fetch/744.html" title="Last updated on Aug 16, 2018, 11:43 AM GMT (e4025ba)">Preview</a> | <a href="https://whatpr.org/fetch/744/e2d62ff...e4025ba.html" title="Last updated on Aug 16, 2018, 11:43 AM GMT (e4025ba)">Diff</a>
> Editorial: turn CORS-preflight cache into a list

- fetch.bs
Tests: already tested by fetch/api/redirect/redirect-method.any.js.
Fixes #753.
***
<a href="https://whatpr.org/fetch/796.html" title="Last updated on Aug 17, 2018, 2:28 PM GMT (ab512d2)">Preview</a> | <a href="https://whatpr.org/fetch/796/6c1174d...ab512d2.html" title="Last updated on Aug 17, 2018, 2:28 PM GMT (ab512d2)">Diff</a>
> Preserve HEAD method on 303 redirect

- fetch.bs
And linkify TypeError.
Fixes #513.
***
<a href="https://whatpr.org/fetch/794.html" title="Last updated on Aug 20, 2018, 10:42 AM GMT (c998afe)">Preview</a> | <a href="https://whatpr.org/fetch/794/6c1174d...c998afe.html" title="Last updated on Aug 20, 2018, 10:42 AM GMT (c998afe)">Diff</a>
> Editorial: use Infra maps for dictionaries

- fetch.bs
***
<a href="https://whatpr.org/fetch/797.html" title="Last updated on Aug 17, 2018, 2:37 PM GMT (0adb713)">Preview</a> | <a href="https://whatpr.org/fetch/797/6c1174d...0adb713.html" title="Last updated on Aug 17, 2018, 2:37 PM GMT (0adb713)">Diff</a>
> Editorial: consistify "one of the following" usage

- fetch.bs
We had decided to change the name of FetchEvent.targetClientId to
.replacesClientId to clarify the meaning that this client is a to be replaced
client: https://github.com/w3c/ServiceWorker/issues/1091#issuecomment-342569083.
Accordingly, this changes the name of the request's target client id item to
replaces client id.
Related issue: https://github.com/w3c/ServiceWorker/issues/1245.
SW PR: https://github.com/w3c/ServiceWorker/pull/1333.
HTML PR: https://github.com/whatwg/html/pull/3788.
***
<a href="https://whatpr.org/fetch/774.html" title="Last updated on Jul 1, 2018, 11:25 PM GMT (bc2ba08)">Preview</a> | <a href="https://whatpr.org/fetch/774/e6cbef2...bc2ba08.html" title="Last updated on Jul 1, 2018, 11:25 PM GMT (bc2ba08)">Diff</a>
> Change name from target client id to replaces client id

- fetch.bs
This also introduces "safely extract" which mainly serves to make it explicit which extraction operations cannot throw.
Tests: ...
Fixes #792.
***
<a href="https://whatpr.org/fetch/801.html" title="Last updated on Aug 23, 2018, 6:47 AM GMT (eeadb52)">Preview</a> | <a href="https://whatpr.org/fetch/801/5088fce...eeadb52.html" title="Last updated on Aug 23, 2018, 6:47 AM GMT (eeadb52)">Diff</a>
> Make extract throw for a disturbed/locked ReadableStream

- fetch.bs
Use "append" instead of "set" to modify the header list, improving
consistency (#758).
/cc @annevk @youennf
***
<a href="https://whatpr.org/fetch/807.html" title="Last updated on Sep 10, 2018, 12:33 PM GMT (2bd2f6b)">Preview</a> | <a href="https://whatpr.org/fetch/807/1bda545...2bd2f6b.html" title="Last updated on Sep 10, 2018, 12:33 PM GMT (2bd2f6b)">Diff</a>
> Editorial: Use "append" to modify the header list

- fetch.bs
This was forgotten in 9288c8f85c809a0ac371be6843ad2cf4046ee35b.
***
<a href="https://whatpr.org/fetch/815.html" title="Last updated on Oct 17, 2018, 9:00 AM GMT (78fca7b)">Preview</a> | <a href="https://whatpr.org/fetch/815/daca6a8...78fca7b.html" title="Last updated on Oct 17, 2018, 9:00 AM GMT (78fca7b)">Diff</a>
> Editorial: remove leftover sentence

- fetch.bs
As discussed in https://bugzilla.mozilla.org/show_bug.cgi?id=1030660 if this is needed at all it should have a different architecture. No other browser is interested in implementing this either.
***
<a href="https://whatpr.org/fetch/816.html" title="Last updated on Oct 17, 2018, 9:17 AM GMT (c03740b)">Preview</a> | <a href="https://whatpr.org/fetch/816/daca6a8...c03740b.html" title="Last updated on Oct 17, 2018, 9:17 AM GMT (c03740b)">Diff</a>
> Remove Gecko-only quirk

- fetch.bs
And add some of the infrastructure needed to define parsing better for all headers going forward (needed for #814). Fixes #752.
This also fixes an issue with CORB as it simply assumed an X-Content-Type-Options was present.
Tests: https://github.com/web-platform-tests/wpt/pull/13559.
***
<a href="https://whatpr.org/fetch/818.html" title="Last updated on Oct 31, 2018, 9:14 AM GMT (3515d9b)">Preview</a> | <a href="https://whatpr.org/fetch/818/daca6a8...3515d9b.html" title="Last updated on Oct 31, 2018, 9:14 AM GMT (3515d9b)">Diff</a>
> Define parsing for X-Content-Type-Options in detail

- fetch.bs
In particular, make it use header list's get operation to retrieve the Access-Control-Allow-Origin and Access-Control-Allow-Credentials values.
Tests: https://github.com/web-platform-tests/wpt/pull/13815.
> Refactor the CORS check

- fetch.bs
I hope this PR has what should be done(#817).
If need some adjustment, I can do.
***
<a href="https://whatpr.org/fetch/830.html" title="Last updated on Nov 7, 2018, 11:35 AM GMT (1893d47)">Preview</a> | <a href="https://whatpr.org/fetch/830/3fb65a0...1893d47.html" title="Last updated on Nov 7, 2018, 11:35 AM GMT (1893d47)">Diff</a>
> Editorial: drop parenthesis around variables

- fetch.bs
Tests: https://github.com/web-platform-tests/wpt/pull/13921.
Helps with #814.
> Be strict on request's Content-Type

- fetch.bs
See https://github.com/whatwg/mimesniff/pull/90.
***
<a href="https://whatpr.org/fetch/828.html" title="Last updated on Nov 12, 2018, 9:28 AM GMT (57b9f55)">Preview</a> | <a href="https://whatpr.org/fetch/828/32c7b1c...57b9f55.html" title="Last updated on Nov 12, 2018, 9:28 AM GMT (57b9f55)">Diff</a>
> Add HTTP whitespace back for MIME types

- fetch.bs
This also addresses #737 in that now A -> B -> A would be considered cross-origin even for "no-cors", but leaving that open for further plumbing in HTML et al to override that in select cases (e.g., `<img>`).
Fixes #756.
***
<a href="https://whatpr.org/fetch/834.html" title="Last updated on Nov 19, 2018, 10:02 AM GMT (dca2295)">Preview</a> | <a href="https://whatpr.org/fetch/834/ba2fb9c...dca2295.html" title="Last updated on Nov 19, 2018, 10:02 AM GMT (dca2295)">Diff</a>
> Take tainted origin flag into account for the same origin check

- fetch.bs
Also known as "extract a MIME type" down right.
Tests: https://github.com/web-platform-tests/wpt/pull/10525.
Helps with #814.
Fixes #529. Closes https://github.com/whatwg/mimesniff/issues/30.
***
<a href="https://whatpr.org/fetch/831.html" title="Last updated on Nov 22, 2018, 1:38 PM GMT (eed035b)">Preview</a> | <a href="https://whatpr.org/fetch/831/a243f1f...eed035b.html" title="Last updated on Nov 22, 2018, 1:38 PM GMT (eed035b)">Diff</a>
> Define the Content-Type header parser

- fetch.bs
If the headers doesn't contain entries for |name|, |temporaryValue|
should be |value|, not the combined value followed by 0x2c 0x20
followed by |value|.
***
<a href="https://whatpr.org/fetch/840.html" title="Last updated on Nov 28, 2018, 1:14 AM GMT (991adf3)">Preview</a> | <a href="https://whatpr.org/fetch/840/0b2bc05...991adf3.html" title="Last updated on Nov 28, 2018, 1:14 AM GMT (991adf3)">Diff</a>
> Fix: Appending a header to headers with "request-no-cors" guard

- fetch.bs
Downloading resources over FTP is dangerous in itself, as FTP is a non-securable
protocol. But rendering resources as 'text/html' or similar is even more
dangerous for a variety of reasons (explored to some extent in the blink-dev@
thread linked below). This patch forces FTP resources into an
'application/octet-stream' MIME type, which should prevent them from rendering
as HTML in user agents.
https://groups.google.com/a/chromium.org/d/msg/blink-dev/eopgOoY1QLs/e1tIefOxAAAJ
Closes whatwg/html#4178
***
<a href="https://whatpr.org/fetch/839.html" title="Last updated on Nov 30, 2018, 8:21 AM GMT (55e9f18)">Preview</a> | <a href="https://whatpr.org/fetch/839/0b2bc05...55e9f18.html" title="Last updated on Nov 30, 2018, 8:21 AM GMT (55e9f18)">Diff</a>
> Treat resources requested via FTP as binary data.

- fetch.bs
The model described does not match implementations and there's only support from a single implementation at this point.
#726 works on reintroducing this feature with broader support and a better model.
Closes #867.
***
<a href="https://whatpr.org/fetch/884.html" title="Last updated on Mar 23, 2019, 9:26 AM UTC (4b9bb07)">Preview</a> | <a href="https://whatpr.org/fetch/884/265974f...4b9bb07.html" title="Last updated on Mar 23, 2019, 9:26 AM UTC (4b9bb07)">Diff</a>
> Remove Client Hints

- fetch.bs
Define a new cache mode "async-stale-revalidated" to indicate that the
fetch stack should return a stale response if it can and aysnchronously
revalidate the response.
Fixes #852
***
<a href="https://whatpr.org/fetch/853.html" title="Last updated on May 3, 2019, 12:53 PM UTC (e17297b)">Preview</a> | <a href="https://whatpr.org/fetch/853/6a644c6...e17297b.html" title="Last updated on May 3, 2019, 12:53 PM UTC (e17297b)">Diff</a>
> Add Stale While Revalidate Handling

- fetch.bs
Let Origin header honor referrer policy for non CORS request
Tests: https://github.com/web-platform-tests/wpt/pull/14260
***
<a href="https://whatpr.org/fetch/908.html" title="Last updated on Jun 26, 2019, 12:41 PM UTC (81c4f70)">Preview</a> | <a href="https://whatpr.org/fetch/908/49b92ee...81c4f70.html" title="Last updated on Jun 26, 2019, 12:41 PM UTC (81c4f70)">Diff</a>
> Let Origin header honor referrer policy for non CORS request

- fetch.bs
a simple fix
***
<a href="https://whatpr.org/fetch/914.html" title="Last updated on Jul 4, 2019, 2:28 AM UTC (cf898fa)">Preview</a> | <a href="https://whatpr.org/fetch/914/49b92ee...cf898fa.html" title="Last updated on Jul 4, 2019, 2:28 AM UTC (cf898fa)">Diff</a>
> Remove brief to unhide the note in fetch-redirect

- fetch.bs
CORS preflight requests' `mode` is now exposed via the `Sec-Fetch-Mode` header, and it
makes sense to set it to `cors`, as it's part of the CORS protocol.
Fixes https://github.com/w3c/webappsec-fetch-metadata/issues/35.
***
<a href="https://whatpr.org/fetch/916.html" title="Last updated on Jul 16, 2019, 12:31 PM UTC (f74a395)">Preview</a> | <a href="https://whatpr.org/fetch/916/7e088f6...f74a395.html" title="Last updated on Jul 16, 2019, 12:31 PM UTC (f74a395)">Diff</a>
> Set CORS preflight requests' `mode` to `cors`.

- fetch.bs
@domenic it would probably make the most sense for Infra to define "byte less than", right?
***
<a href="https://whatpr.org/fetch/906.html" title="Last updated on Aug 8, 2019, 8:35 AM UTC (f16e13e)">Preview</a> | <a href="https://whatpr.org/fetch/906/2d0d7bd...f16e13e.html" title="Last updated on Aug 8, 2019, 8:35 AM UTC (f16e13e)">Diff</a>
> Editorial: defining header name sorting

- fetch.bs
See https://github.com/heycam/webidl/issues/795 for context.
***
<a href="https://whatpr.org/fetch/937.html" title="Last updated on Sep 13, 2019, 1:38 PM UTC (f88f188)">Preview</a> | <a href="https://whatpr.org/fetch/937/60a516d...f88f188.html" title="Last updated on Sep 13, 2019, 1:38 PM UTC (f88f188)">Diff</a>
> Editorial: stop using "promise-calling"

- fetch.bs
As discussed in w3c/webappsec-fetch-metadata#40, this patch takes a
small first step towards supporting Structure Header values in Fetch by
wrapping header lists' existing "set" algorithm with a version that
first serializes a Structured Header object into a string
representation.
***
<a href="https://whatpr.org/fetch/925.html" title="Last updated on Sep 13, 2019, 1:52 PM UTC (fb49277)">Preview</a> | <a href="https://whatpr.org/fetch/925/ce287b0...fb49277.html" title="Last updated on Sep 13, 2019, 1:52 PM UTC (fb49277)">Diff</a>
> "Set" Structured Header values in header lists.

- fetch.bs
I'm not certain it's right to scope this under `header list`, but "determine nosniff" doesn't seem like it scopes itself well enough to leave it global.
I'm hoping to call this (or anything better you might suggest) from https://github.com/WICG/webpackage/pull/348, where @mikewest encouraged me to require the new format to always be served with the nosniff header.
***
<a href="https://whatpr.org/fetch/851.html" title="Last updated on Dec 19, 2018, 10:28 PM UTC (4bba761)">Preview</a> | <a href="https://whatpr.org/fetch/851/c6b3a75...4bba761.html" title="Last updated on Dec 19, 2018, 10:28 PM UTC (4bba761)">Diff</a>
> Export "determine nosniff".

- fetch.bs
This fixes issue https://github.com/whatwg/fetch/issues/921
***
<a href="https://whatpr.org/fetch/947.html" title="Last updated on Oct 5, 2019, 10:52 AM UTC (3ea8573)">Preview</a> | <a href="https://whatpr.org/fetch/947/412723b...3ea8573.html" title="Last updated on Oct 5, 2019, 10:52 AM UTC (3ea8573)">Diff</a>
> Fixes Issue-921 : "The above steps prevent the following attack at..."

- fetch.bs
Tests: https://github.com/web-platform-tests/wpt/pull/17589?
Closes #650.
***
<a href="https://whatpr.org/fetch/915.html" title="Last updated on Jul 2, 2019, 12:38 PM UTC (ba239a1)">Preview</a> | <a href="https://whatpr.org/fetch/915/cc80ec5...ba239a1.html" title="Last updated on Jul 2, 2019, 12:38 PM UTC (ba239a1)">Diff</a>
> Use UTF-8 decode without BOM for multipart/form-data

- fetch.bs
As far as I can tell we use "response tainting" for the same thing.
This also fixes an issue whereby we checked origin tainting rather than response tainting in main fetch which results in a minor bug when it comes to opaquing A -> B -> A chains.
***
<a href="https://whatpr.org/fetch/960.html" title="Last updated on Nov 11, 2019, 8:50 AM UTC (70ffc79)">Preview</a> | <a href="https://whatpr.org/fetch/960/7db8ac5...70ffc79.html" title="Last updated on Nov 11, 2019, 8:50 AM UTC (70ffc79)">Diff</a>
> Remove the CORS flag

- fetch.bs
Follows https://github.com/whatwg/html/pull/5076.
/cc @mikewest 
I'm unsure whether this should be "same site" or "schemelessly same site". I guess for parity with the previous it should be "schemelessly same site"? But that seems like a pretty bad mismatch with the web-dev-visible header name... what's going on?
***
<a href="https://whatpr.org/fetch/965.html" title="Last updated on Nov 19, 2019, 5:01 PM UTC (1d6002f)">Preview</a> | <a href="https://whatpr.org/fetch/965/65138f3...1d6002f.html" title="Last updated on Nov 19, 2019, 5:01 PM UTC (1d6002f)">Diff</a>
> Editorial: use origin-based "same site" definition

- fetch.bs
This adds a Timing Allow Origin (TAO) check, trying to be as close to a CORS check as possible. The check is added very close to where the CORS check is, in the HTTP fetch algorithm. It is added so that service worker responses are also checked. When the check fails, it is stored in the request (and once it fails, future redirects cannot cause it to pass). This check is similar to https://w3c.github.io/resource-timing/#dfn-timing-allow-check but the tainted bool is replaced with the tainted origin flag to align with CORS.
***
<a href="https://whatpr.org/fetch/955.html" title="Last updated on Dec 3, 2019, 6:27 PM UTC (648f46e)">Preview</a> | <a href="https://whatpr.org/fetch/955/ae6435f...648f46e.html" title="Last updated on Dec 3, 2019, 6:27 PM UTC (648f46e)">Diff</a>
> Add TAO check

- fetch.bs
***
<a href="https://whatpr.org/fetch/977.html" title="Last updated on Dec 9, 2019, 6:56 PM UTC (23ecbb3)">Preview</a> | <a href="https://whatpr.org/fetch/977/493c021...23ecbb3.html" title="Last updated on Dec 9, 2019, 6:56 PM UTC (23ecbb3)">Diff</a>
> strip request-body-header for redireting from POST to GET

- fetch.bs
As noted in https://github.com/whatwg/fetch/issues/772#issuecomment-564515727 the current way it is exposed subsets what HTTP supports and therefore does not feel like a good starting point. Both for the internal and public API.
Additionally, the public-facing API has not seen interest from implementers, at least for the past year and a half.
***
<a href="https://whatpr.org/fetch/979.html" title="Last updated on Dec 11, 2019, 12:32 PM UTC (93b4349)">Preview</a> | <a href="https://whatpr.org/fetch/979/9dd5319...93b4349.html" title="Last updated on Dec 11, 2019, 12:32 PM UTC (93b4349)">Diff</a>
> Remove trailer support

- fetch.bs
We have used an imprecise sentence for creating a ReadableStream "from which
one can read the exactly same data as one could read" from the original
ReadableStream, because transform streams and piping were not defined. Now they
are available, so let's use them.
Fixes #463.
***
<a href="https://whatpr.org/fetch/959.html" title="Last updated on Dec 13, 2019, 9:03 AM UTC (81c5b23)">Preview</a> | <a href="https://whatpr.org/fetch/959/7db8ac5...81c5b23.html" title="Last updated on Dec 13, 2019, 9:03 AM UTC (81c5b23)">Diff</a>
> Use ReadableStreamPipeTo in Request constructor

- fetch.bs
As discussed in #930 and mikewest/corpp#2, this patch adds a "get"
method on header lists that allows consistent extraction of
structured headers.
***
<a href="https://whatpr.org/fetch/983.html" title="Last updated on Dec 21, 2019, 8:54 AM UTC (9125901)">Preview</a> | <a href="https://whatpr.org/fetch/983/b93383c...9125901.html" title="Last updated on Dec 21, 2019, 8:54 AM UTC (9125901)">Diff</a>
> "Get" a structured header from a header list.

- fetch.bs
Already covered by web-platform-tests.
Fixes #990.
***
<a href="https://whatpr.org/fetch/992.html" title="Last updated on Jan 9, 2020, 10:36 AM UTC (14f2982)">Preview</a> | <a href="https://whatpr.org/fetch/992/8ca6148...14f2982.html" title="Last updated on Jan 9, 2020, 10:36 AM UTC (14f2982)">Diff</a>
> Change the Access-Control-Max-Age default to 5

- fetch.bs
This patch adds `cross-site` to the list of allowed CORP header values. It's a no-op
at this point, but I've started asking folks to set this header in preparation for COEP
rollout, and one has pointed me to the spec, noting that the value I'm suggesting they
add isn't technically legal.
***
<a href="https://whatpr.org/fetch/1016.html" title="Last updated on Apr 1, 2020, 2:32 PM UTC (1665249)">Preview</a> | <a href="https://whatpr.org/fetch/1016/00239c1...1665249.html" title="Last updated on Apr 1, 2020, 2:32 PM UTC (1665249)">Diff</a>
> Add `cross-origin` to allowed CORP header values.

- fetch.bs
See https://github.com/whatwg/url/pull/503.
(This needs to wait for that PR to actually land + a day or so.)
***
<a href="https://whatpr.org/fetch/1026.html" title="Last updated on May 12, 2020, 7:10 AM UTC (f66370b)">Preview</a> | <a href="https://whatpr.org/fetch/1026/8d64fa2...f66370b.html" title="Last updated on May 12, 2020, 7:10 AM UTC (f66370b)">Diff</a>
> Meta: URL changed how it exports percent-decode

- fetch.bs
This is a preliminary change for COEP merging to the HTML and fetch specs.
We will use the serialization multiple times both in the HTML spec and
the fetch spec, so defining the operation here will be benefitial.
There's no behavior change.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jun 2, 2020, 8:25 AM UTC)_.
<details>
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fwhatwg%2Ffetch%2F1298cde97a5e66dbd2de5602afa9098 …
> Define "Request URL serialization for reporting"

- fetch.bs
Part of https://github.com/whatwg/xhr/issues/277, removing `ReadableStream` from the body init used by XHR, and re-defining a `BodyInit` to include the stream option.
* Mozilla cc @annevk
* Google cc @yutakahirano
* I think this should not affect existing tests in fetch, for xhr see https://github.com/whatwg/xhr/issues/277
* None are filed because the changes here described the current behavior.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jun 2, 2020, 4:27 PM UTC)_.
<details>
:rotating_light: [CSS Spec …
> Define a XMLHttpRequestBodyInit without ReadableStream

- fetch.bs
As discussed in w3c/webappsec-fetch-metadata#45, splitting 'document' into a set of
destination values that developers can use to determine whether the request is for
a top-level document or a nested document will allow us to simplify Fetch Metadata
checks performed server side.
***
<a href="https://whatpr.org/fetch/948.html" title="Last updated on Jun 5, 2020, 8:23 AM UTC (939613d)">Preview</a> | <a href="https://whatpr.org/fetch/948/9ac2b5b...939613d.html" title="Last updated on Jun 5, 2020, 8:23 AM UTC (939613d)">Diff</a>
> Revisit `destination` for `<iframe>`, `<frame>`, `<embed>`, and `<object>`.

- README.md
Add style rules for new lines and names.
> Add style rules

- fetch.bs
This is part of the introduction of COEP
(https://github.com/whatwg/html/pull/5454). The CORP check now takes
COEP into account. Also, responses coming from service workers
are checked.
***
<a href="https://whatpr.org/fetch/1030.html" title="Last updated on Jun 26, 2020, 7:14 AM UTC (ea40eaf)">Preview</a> | <a href="https://whatpr.org/fetch/1030/b228c33...ea40eaf.html" title="Last updated on Jun 26, 2020, 7:14 AM UTC (ea40eaf)">Diff</a>
> Integrate CORP and COEP

- fetch.bs
Adds a section to define the HTTP cache associated with a request as per HTTP cache partitioning.
github issue: https://github.com/whatwg/fetch/issues/904
Explainer: https://github.com/shivanigithub/http-cache-partitioning/
***
<a href="https://whatpr.org/fetch/943.html" title="Last updated on Jun 9, 2020, 5:59 AM UTC (5e45c5b)">Preview</a> | <a href="https://whatpr.org/fetch/943/57305b8...5e45c5b.html" title="Last updated on Jun 9, 2020, 5:59 AM UTC (5e45c5b)">Diff</a>
> HTTP cache partitioning

- fetch.bs
Fixes #780. Fixes #976. Follows https://github.com/whatwg/streams/pull/1045.
(At least, I think this fixes #976. That's a long issue with lots of text, but this significantly reduces the amount of "in parallel" that happens in upload streaming, so it seems likely to address the problem.)
This should land after https://github.com/whatwg/streams/pull/1045 and needs some updates once it does, so tagging "do not merge yet". But it's ready for review.
The "looping" algorithms could potentially use better names; bikeshed help welcome.
***
<a href="https://whatpr.org/fetch/1044.html" title="Last updated on Jul 7, 2020, 4:34 PM UTC (b2777e3)">Preview</a> | <a href="https://whatpr.org/fetch/1044/b228c33...b2777e3.html" title="Last updated on Jul 7, 2020, 4:34 PM UTC (b2777e3)">Diff</a>
> Adapt to changes in Streams

- fetch.bs
HTML now references Fetch and the old CORS specification redirects to Fetch.
***
<a href="https://whatpr.org/fetch/1055.html" title="Last updated on Jul 14, 2020, 2:53 PM UTC (f8db93a)">Preview</a> | <a href="https://whatpr.org/fetch/1055/801dc8b...f8db93a.html" title="Last updated on Jul 14, 2020, 2:53 PM UTC (f8db93a)">Diff</a>
> Meta: update Goals

- fetch.bs
As well as a typo.
Closes #894 and closes #895.
***
<a href="https://whatpr.org/fetch/1057.html" title="Last updated on Jul 15, 2020, 8:46 AM UTC (728b7c2)">Preview</a> | <a href="https://whatpr.org/fetch/1057/d70b26a...728b7c2.html" title="Last updated on Jul 15, 2020, 8:46 AM UTC (728b7c2)">Diff</a>
> Correct some header list append invocations

- fetch.bs
All usage of structured fields in the web platform should not distinguish between the header not being there and failing to parse per the structured field parsing algorithm.
This also aligns Fetch slightly with terminology changes in HTTP that more clearly separate headers and trailers.
A future change might rename other concepts to also align with that (e.g., header list to field list).
Fixes #1053.
***
<a href="https://whatpr.org/fetch/1056.html" title="Last updated on Jul 15, 2020, 4:41 AM UTC (b15a670)">Preview</a> | <a href="https://whatpr.org/fetch/1056/801dc8b...b15a670.html" title="Last updated on Jul 15, 2020, 4:41 AM UTC (b15a670)">Diff</a>
> Return null if parsing a structured field value fails

- fetch.bs
Use "this" and "x steps are". Also use the relevant settings object in constructors, rather than current. (They are identical there, but it's better to encourage relevant.)
***
<a href="https://whatpr.org/fetch/1054.html" title="Last updated on Jul 15, 2020, 5:51 AM UTC (0744a98)">Preview</a> | <a href="https://whatpr.org/fetch/1054/801dc8b...0744a98.html" title="Last updated on Jul 15, 2020, 5:51 AM UTC (0744a98)">Diff</a>
> Editorial: align with new IDL patterns

- fetch.bs
Part of #1062. Closes #270.
* All implementers do not use the HTTPS state concept. Apparently Chrome did at one time, but I checked and we're OK removing it.
* This isn't really testable, I don't think?
* N/A
***
<a href="https://whatpr.org/fetch/1067.html" title="Last updated on Aug 4, 2020, 4:54 PM UTC (62b107f)">Preview</a> | <a href="https://whatpr.org/fetch/1067/4ad496d...62b107f.html" title="Last updated on Aug 4, 2020, 4:54 PM UTC (62b107f)">Diff</a>
> Remove HTTPS state concept

- fetch.bs
Extend the HTTP cache partitioning logic to partition connections as well. This doesn't cover everything that will need to be partitioned, since much of it isn't even capturing in the fetch spec yet (browser-managed DNS caches, WebSocket connections over H2/H3 proxies, H2/H3 sessions, TLS/H3 session resumption cache, cache of metadata about H3-capable servers, HTTP auth cache, etc).
This addresses parts of issue #917.
* Chrome
* FireFox
* ...
* Chrome: https://crbug.com/963480
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1572544
* Safari: …
***
<a href="https://whatpr.org/fetch/1063.html" title="Last updated on Aug 6, 2020, 2:51 PM UTC (8cbe436)">Preview</a> | <a href="https://whatpr.org/fetch/1063/4ad496d...8cbe436.html" title="Last updated on Aug 6, 2020, 2:51 PM UTC …
> Partition HTTP Connections

- fetch.bs
And remove a confusing note.
Closes #1068.
***
<a href="https://whatpr.org/fetch/1069.html" title="Last updated on Aug 6, 2020, 2:42 PM UTC (3e0b5da)">Preview</a> | <a href="https://whatpr.org/fetch/1069/44a94a6...3e0b5da.html" title="Last updated on Aug 6, 2020, 2:42 PM UTC (3e0b5da)">Diff</a>
> Add examples for collect an HTTP quoted string

- fetch.bs
Fixes #1074.
I think this is all it needs, because otherwise we want the header guard to be "request".
***
<a href="https://whatpr.org/fetch/1076.html" title="Last updated on Aug 18, 2020, 2:10 PM UTC (6fdbcde)">Preview</a> | <a href="https://whatpr.org/fetch/1076/1b1239a...6fdbcde.html" title="Last updated on Aug 18, 2020, 2:10 PM UTC (6fdbcde)">Diff</a>
> Set request header's guard if no-cors

- fetch.bs
***
<a href="https://whatpr.org/fetch/1084.html" title="Last updated on Aug 27, 2020, 7:18 AM UTC (de1d0fc)">Preview</a> | <a href="https://whatpr.org/fetch/1084/99db8c2...de1d0fc.html" title="Last updated on Aug 27, 2020, 7:18 AM UTC (de1d0fc)">Diff</a>
> Meta: disambiguate fetch() from the CSS function with the same name

- fetch.bs
Follows https://github.com/whatwg/streams/pull/1073.
***
<a href="https://whatpr.org/fetch/1085.html" title="Last updated on Sep 15, 2020, 9:33 AM UTC (b5d273c)">Preview</a> | <a href="https://whatpr.org/fetch/1085/cd38eca...b5d273c.html" title="Last updated on Sep 15, 2020, 9:33 AM UTC (b5d273c)">Diff</a>
> Use new Streams algorithms

- fetch.bs
(Perhaps at some point it makes sense to determine the key once and store it on the request. For now I think this is okay, but let me know if you feel otherwise.)
cc @MattMenke2 @shivanigithub
***
<a href="https://whatpr.org/fetch/1101.html" title="Last updated on Oct 12, 2020, 1:18 PM UTC (3d38857)">Preview</a> | <a href="https://whatpr.org/fetch/1101/5321d4a...3d38857.html" title="Last updated on Oct 12, 2020, 1:18 PM UTC (3d38857)">Diff</a>
> Use the network partition key in the CORS-preflight cache

- fetch.bs
Closes #750.
***
<a href="https://whatpr.org/fetch/1107.html" title="Last updated on Nov 2, 2020, 2:08 PM UTC (6c00440)">Preview</a> | <a href="https://whatpr.org/fetch/1107/515e6bb...6c00440.html" title="Last updated on Nov 2, 2020, 2:08 PM UTC (6c00440)">Diff</a>
> Editorial: align bad port service names with IANA

- fetch.bs
This is a re-do of #952 started by @mikewest since I am taking over the relevant spec updates.
This spec will now point to a constant defined in w3c/webappsec-referrer-policy/pull/142 as the default referrer policy.
***
<a href="https://whatpr.org/fetch/1066.html" title="Last updated on Nov 30, 2020, 12:23 PM UTC (735829a)">Preview</a> | <a href="https://whatpr.org/fetch/1066/c5f8177...735829a.html" title="Last updated on Nov 30, 2020, 12:23 PM UTC (735829a)">Diff</a>
> Point default referrer policy to a constant defined in RP spec

- fetch.bs
Tests: https://github.com/web-platform-tests/wpt/pull/27100.
Closes #1135.
* Firefox
* Chrome
* https://github.com/web-platform-tests/wpt/pull/27100
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1165671
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1684634
* Safari: https://bugs.webkit.org/show_bug.cgi?id=220535
***
<a href="https://whatpr.org/fetch/1137.html" title="Last updated on Jan 12, 2021, 7:51 AM UTC (b1258bb)">Preview</a> | <a href="https://whatpr.org/fetch/1137/f7a81a0...b1258bb.html" title="Last updated on Jan 12, 2021, 7:51 AM UTC (b1258bb)">Diff</a>
> Turn Body mixin's MIME type into a getter

- fetch.bs
Closes #802.
***
<a href="https://whatpr.org/fetch/1155.html" title="Last updated on Jan 30, 2021, 3:15 PM UTC (b2c63cd)">Preview</a> | <a href="https://whatpr.org/fetch/1155/d070ea2...b2c63cd.html" title="Last updated on Jan 30, 2021, 3:15 PM UTC (b2c63cd)">Diff</a>
> Editorial: Body mixin cleanup

- fetch.bs
This only affects specifications that do not set credentials mode and I'm not aware of any.
Closes #804.
***
<a href="https://whatpr.org/fetch/1153.html" title="Last updated on Jan 30, 2021, 11:21 AM UTC (587b2aa)">Preview</a> | <a href="https://whatpr.org/fetch/1153/d070ea2...587b2aa.html" title="Last updated on Jan 30, 2021, 11:21 AM UTC (587b2aa)">Diff</a>
> Change default of request's credentials mode

- fetch.bs
Closes #771.
***
<a href="https://whatpr.org/fetch/1157.html" title="Last updated on Feb 2, 2021, 10:50 AM UTC (64f061a)">Preview</a> | <a href="https://whatpr.org/fetch/1157/98f23db...64f061a.html" title="Last updated on Feb 2, 2021, 10:50 AM UTC (64f061a)">Diff</a>
> Add abstractions for creating Request and Response objects

- fetch.bs
It does not need to be stored on a response and therefore resulted in confusion.
Also clarify that synthetic responses need to have an absolute URL in the Location header field value (Response.redirect() does this automatically).
Corresponding HTML PR: TODO.
Tests: TODO.
Closes #631, closes #633, closes #958, and closes #1146. (Some of these can be closed due to #1030 making response's URL no longer null for network responses.)
* Chrome
* Firefox
* https://chromium-review.googlesource.com/c/chromium/src/+/2665871
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1170379
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1690286
* Safari: N/A
***
<a …
> Remove location URL as field on responses

- fetch.bs
For the Headers class, Body mixin, Request's clone(), and the Response class.
Closes #543.
----
I would very much appreciate review in the form of fixup commits as this is extremely tedious work. 😊 I didn't really try to tackle any greater style questions, though I would be (more) inclined to address suggestions there as I realize that could use some renewal, especially now that JavaScript has destructuring.
***
<a href="https://whatpr.org/fetch/1161.html" title="Last updated on Feb 4, 2021, 10:12 AM UTC (a2090d5)">Preview</a> | <a href="https://whatpr.org/fetch/1161/89cfc1d...a2090d5.html" title="Last updated on Feb 4, 2021, 10:12 AM UTC (a2090d5)">Diff</a>
> Add remaining domintro boxes

- fetch.bs
There is no need for the fetch() method to go in parallel to run fetch as the main fetch algorithm already does that itself. This also prevents the issue of the main fetch algorithm grabbing global state at the wrong time.
***
<a href="https://whatpr.org/fetch/1163.html" title="Last updated on Feb 8, 2021, 1:44 PM UTC (f4bcad7)">Preview</a> | <a href="https://whatpr.org/fetch/1163/e5500e5...f4bcad7.html" title="Last updated on Feb 8, 2021, 1:44 PM UTC (f4bcad7)">Diff</a>
> fetch() does not need in parallel as fetch already does so

- fetch.bs
Any fetching of ftp: URLs will now result in a network error.
This also removes network scheme in favor of using HTTP(S) scheme exclusively.
Closes #1009.
* Chrome
* Firefox
* https://github.com/web-platform-tests/wpt/issues/17836 (wontfix)
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=333943
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1574475
* Safari: https://bugs.webkit.org/show_bug.cgi?id=221675
***
<a href="https://whatpr.org/fetch/1166.html" title="Last updated on Feb 10, 2021, 4:04 PM UTC (3140ae4)">Preview</a> | <a href="https://whatpr.org/fetch/1166/c8c2b62...3140ae4.html" title="Last updated on Feb 10, 2021, 4:04 PM UTC (3140ae4)">Diff</a>
> Remove FTP support

- fetch.bs
This makes some rather big changes:
* Requests no longer have a synchronous flag. Blocking a thread is now up to the caller.
* Fetch therefore no longer returns a response directly. In parallel callers will need to pass in "callbacks" that are either invoked on a parallel queue or on an event loop.
* To hold onto these callbacks as well as some other information a fetch params struct is now passed around the various fetch algorithms. This will allow for cleanup around termination and aborting in the future. Potentially some bookkeeping state from request can move there going forward.
* There's a dedicated navigate-redirect fetch algorithm for HTML as the HTTP-redirect fetch algorithm now wants a fetch params instance.
* Some allowance for aborting early on in fetch was removed as all that …
> Overhaul how standards integrate with fetch

- fetch.bs
This change clarifies a (non-normative) statement that "cors" request mode is what makes a request into a cors request. In fact, for requests with "cors" request mode, "cors" response tainting is also necessary in order for the request to be considered a cors request. So this change refines the relevant statement to make that clear.
Otherwise, without this change, considering the case of a same-origin GET request whose mode is "cors", the spec is claiming that same-origin GET request is a cors request.
But because the spec defines a "cors request" as “an HTTP request that includes an `Origin` header”, a same-origin GET request cannot in fact be a cors request — because it doesn’t include an `Origin` header. (And that’s because for GET requests, the spec requires an `Origin` header to be …
> Clarify cors requests need cors response tainting

- fetch.bs
* Chrome
* Firefox
* https://github.com/web-platform-tests/wpt/pull/27325
* Chrome: https://crbug.com/1167013
* Firefox: N/A as streaming request body has not been implemented
* Safari: N/A as streaming request body has not been implemented
Fixes w3c/ServiceWorker#1560, fixes #572.
***
<a href="https://whatpr.org/fetch/1144.html" title="Last updated on Feb 17, 2021, 12:27 PM UTC (c13ef6f)">Preview</a> | <a href="https://whatpr.org/fetch/1144/3c90676...c13ef6f.html" title="Last updated on Feb 17, 2021, 12:27 PM UTC (c13ef6f)">Diff</a>
> Tee request body on ServiceWorker interception

- fetch.bs
This change updates the descriptions of all “credentials mode” values, to clarify that the values affect whether browsers use credentials sent back in responses (e.g., any Set-Cookie response headers) — not just whether credentials are sent with the request. Related: https://github.com/mdn/content/pull/2468
***
<a href="https://whatpr.org/fetch/1174.html" title="Last updated on Feb 19, 2021, 2:58 PM UTC (8cc1ae8)">Preview</a> | <a href="https://whatpr.org/fetch/1174/c64f074...8cc1ae8.html" title="Last updated on Feb 19, 2021, 2:58 PM UTC (8cc1ae8)">Diff</a>
> Clarify: credentials param affect response too

- fetch.bs
This simplifies some wording introduced in #425 and aligns it with the recently introduced cloning for service workers.
Fixes #1176.
***
<a href="https://whatpr.org/fetch/1177.html" title="Last updated on Feb 24, 2021, 11:42 AM UTC (dacac24)">Preview</a> | <a href="https://whatpr.org/fetch/1177/00344d2...dacac24.html" title="Last updated on Feb 24, 2021, 11:42 AM UTC (dacac24)">Diff</a>
> Give all bodies a stream

- fetch.bs
Closes #661.
***
<a href="https://whatpr.org/fetch/1172.html" title="Last updated on Feb 24, 2021, 11:51 AM UTC (1b5a8cd)">Preview</a> | <a href="https://whatpr.org/fetch/1172/0f29092...1b5a8cd.html" title="Last updated on Feb 24, 2021, 11:51 AM UTC (1b5a8cd)">Diff</a>
> Formalize reading bodies

- fetch.bs
Part of https://github.com/whatwg/html/issues/4335.
***
<a href="https://whatpr.org/fetch/1179.html" title="Last updated on Feb 24, 2021, 5:27 PM UTC (e7d765b)">Preview</a> | <a href="https://whatpr.org/fetch/1179/6ad9998...e7d765b.html" title="Last updated on Feb 24, 2021, 5:27 PM UTC (e7d765b)">Diff</a>
> Editorial: remove a reference to "responsible document"

- fetch.bs
This clarifies how fragment conflicts between the request's current URL
and the Location header are resolved (the latter wins if non-null).
This is the same for documents and subresources.
Tests: web-platform-tests/wpt#27575.
HTML change: whatwg/html#6391.
Follow-ups: #1167 and #1175.
Fixes #505.
* Firefox
* Chrome
* https://github.com/web-platform-tests/wpt/pull/27575
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1178467
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1690286
* Safari: https://bugs.webkit.org/show_bug.cgi?id=221897
***
<a href="https://whatpr.org/fetch/696.html" title="Last updated on Feb 19, 2021, 10:07 AM UTC (99e0110)">Preview</a> | <a …
> Align redirect fragment handling with HTTP

- fetch.bs
a876e5dc87f5e18732aada8a12f6b8cd6eb39340 made a typo and did not account for it potentially not being a URL.
***
<a href="https://whatpr.org/fetch/1180.html" title="Last updated on Feb 26, 2021, 4:54 PM UTC (30a78d4)">Preview</a> | <a href="https://whatpr.org/fetch/1180/a876e5d...30a78d4.html" title="Last updated on Feb 26, 2021, 4:54 PM UTC (30a78d4)">Diff</a>
> Correct location URL algorithm fragment handling

- fetch.bs
This change is a follow-up to the previous change at https://github.com/whatwg/fetch/commit/00344d2 which clarified the effects of the “credentials mode” value. This change similarly refines the description of the RequestInit/credentials member — while adding a statement that the behavior defaults to "same-origin" if RequestInit/credentials is not specified in the Request instance.
***
<a href="https://whatpr.org/fetch/1178.html" title="Last updated on Mar 1, 2021, 6:48 AM UTC (38d218d)">Preview</a> | <a href="https://whatpr.org/fetch/1178/00344d2...38d218d.html" title="Last updated on Mar 1, 2021, 6:48 AM UTC (38d218d)">Diff</a>
> Clarify RequestInit/credentials affects response

- fetch.bs
As the body concept is refactored for #604, XMLHttpRequest will need to use this algorithm for its events. We also want to require browsers to use this algorithm instead of the one defined by HTTP as part of #1156.
Tests: https://github.com/web-platform-tests/wpt/pull/10548.
* Chrome
* Firefox
* See above.
* Chrome: N/A
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1695931 & https://bugzilla.mozilla.org/show_bug.cgi?id=1696203
* Safari: https://bugs.webkit.org/show_bug.cgi?id=222596
@MattMenke2 I haven't attempted to actually require browsers use this yet. I suspect we want some kind of "HTTP monkey patching" section that outlines the various things we want browsers (and clients that …
> Define Content-Length parser

- fetch.bs
Add more parameters to the "obtain a connection" operation, as we want to create a WebTransport over HTTP/3 connection for WebTransport.
This is for w3c/webtransport#128.
* Chrome
* Firefox
* We'll test this as part of WebTransport
* N/A: This is an infrastructure change needed by WebTransport
***
<a href="https://whatpr.org/fetch/1171.html" title="Last updated on Mar 3, 2021, 2:39 PM UTC (5ba523f)">Preview</a> | <a href="https://whatpr.org/fetch/1171/24a8670...5ba523f.html" title="Last updated on Mar 3, 2021, 2:39 PM UTC (5ba523f)">Diff</a>
> Add more parameters to "obtain a connection"

- fetch.bs
- Chrome
- Firefox
-  [ ] [Tests](https://github.com/web-platform-tests/wpt) are written and can be reviewed and commented upon at:
- https://github.com/web-platform-tests/wpt/pull/27322
Chrome: As-is for non-streaming request. https://crbug.com/1171011 for streaming request.
Firefox: As-is for non-streaming request. N/A as streaming request body has not been implemented
Safari: TBD for non-streaming request.  N/A as streaming request body has not been implemented
Fixes #497, #982
***
<a href="https://whatpr.org/fetch/1141.html" title="Last updated on Mar 5, 2021, 10:19 AM UTC (5efd769)">Preview</a> | <a href="https://whatpr.org/fetch/1141/51a664d...5efd769.html" title="Last updated on Mar 5, …
> Add HTTP fetch step on 421.

- fetch.bs
Together with #1183 this solves the Fetch side of #604. Changes:
* No longer set a length for network responses. Callers will have to parse Content-Length themselves.
* Make extract set length so requests will set Content-Length correctly.
XMLHttpRequest PR: https://github.com/whatwg/xhr/pull/317.
Tests: https://github.com/web-platform-tests/wpt/pull/27837.
* This doesn't really change the requirements and is actually fixing bugs.
* https://github.com/web-platform-tests/wpt/pull/27837
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1186591
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1697421
* Safari: https://bugs.webkit.org/show_bug.cgi?id=223022
***
<a href="https://whatpr.org/fetch/1184.html" title="Last updated on Mar 10, 2021, 11:01 AM UTC …
> Revamp body's total bytes as length

- fetch.bs
Also fix a minor typo in the ABNF definition and remove SRI from the list of things depending on request destination. I don't think it ever did.
Fixes #409.
***
<a href="https://whatpr.org/fetch/1196.html" title="Last updated on Mar 16, 2021, 1:23 PM UTC (2221ec3)">Preview</a> | <a href="https://whatpr.org/fetch/1196/873a42e...2221ec3.html" title="Last updated on Mar 16, 2021, 1:23 PM UTC (2221ec3)">Diff</a>
> Editorial: update Upgrade Insecure Requests reference

- fetch.bs
Created a "fetch timing info" struct to hold the bookkeeping necessary for resource timing.
Populated it with some of the required values, leaving some of them for later patches as this is a big undertaking.
See https://github.com/w3c/resource-timing/issues/252
***
<a href="https://whatpr.org/fetch/1185.html" title="Last updated on Mar 25, 2021, 10:41 AM UTC (66772da)">Preview</a> | <a href="https://whatpr.org/fetch/1185/59da2a4...66772da.html" title="Last updated on Mar 25, 2021, 10:41 AM UTC (66772da)">Diff</a>
> Initial resource timing integration.

- fetch.bs
* Chrome
* Firefox
* https://github.com/web-platform-tests/wpt/pull/28203
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1191310
* Firefox: N/A as streaming request body has not been implemented.
* Safari: N/A as streaming request body has not been implemented.
This change addresses the inconsistency discussed in #267 that a chunk type in stream body on uploading to the network is 
limited only to `Uint8Array` but passing it to a service worker is not restricted.
This PR changes later to limiting `Uint8Array` as well.
***
<a href="https://whatpr.org/fetch/1199.html" title="Last updated on Apr 15, 2021, 2:04 AM UTC (4ad580d)">Preview</a> | <a …
> Add chunk type checking of requestForServiceWorker's body's stream

- fetch.bs
* Chrome
* Firefox
* https://github.com/web-platform-tests/wpt/issues/28568
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1077174
* Firefox: N/A as streaming request body has not been implemented
* Safari: N/A as streaming request body has not been implemented
This fixes #538.
***
<a href="https://whatpr.org/fetch/1204.html" title="Last updated on Apr 19, 2021, 9:34 AM UTC (ff67a7a)">Preview</a> | <a href="https://whatpr.org/fetch/1204/f361d9c...ff67a7a.html" title="Last updated on Apr 19, 2021, 9:34 AM UTC (ff67a7a)">Diff</a>
> Add a limited size buffer for streaming upload in HTTP request.

- fetch.bs
Only call processResponseDone for responses that have their
timing info set, which are responses that have passed CORS
and redirects.
Closes https://github.com/whatwg/fetch/issues/1201
***
<a href="https://whatpr.org/fetch/1202.html" title="Last updated on Apr 21, 2021, 10:57 AM UTC (b455c91)">Preview</a> | <a href="https://whatpr.org/fetch/1202/6453947...b455c91.html" title="Last updated on Apr 21, 2021, 10:57 AM UTC (b455c91)">Diff</a>
> processResponseDone should receive a response

- fetch.bs
This change adds a policy container to the request. The idea is to snapshot the policies when the request is created and have them available for the whole lifetime of the fetch algorithm. Together with a change to CSP, this will solve https://github.com/whatwg/fetch/issues/832.
***
<a href="https://whatpr.org/fetch/1231.html" title="Last updated on May 10, 2021, 10:29 AM UTC (604b99d)">Preview</a> | <a href="https://whatpr.org/fetch/1231/5fac9e8...604b99d.html" title="Last updated on May 10, 2021, 10:29 AM UTC (604b99d)">Diff</a>
> Add policy container to request

- fetch.bs
While [implementing](https://chromium-review.googlesource.com/c/chromium/src/+/2878693) the recent [Resource Timing transferSize changes](https://github.com/w3c/resource-timing/pull/266), I realized that the current spec is not sufficient to implement what was discussed in the WG, and more importantly, insufficient to maintain backwards compatibility with current `transferSize` values.
Essentially, we want `transferSize` to return different values for the cases of local caching (in which case it needs to return 0), full fetch from the network (in which case it needs to return the encoded body size + a constant) as well as the *successful revalidation* case (where it needs to return *just* the constant representing the headers used to revalidate the response).
For that purpose, the "cache …
> Add a "revalidated" cache state

- fetch.bs
ReSpec-authored specifications are best anchored as otherwise outgoing links go all over the map.
***
<a href="https://whatpr.org/fetch/1224.html" title="Last updated on May 25, 2021, 6:42 PM UTC (8080de9)">Preview</a> | <a href="https://whatpr.org/fetch/1224/208e271...8080de9.html" title="Last updated on May 25, 2021, 6:42 PM UTC (8080de9)">Diff</a>
> Meta: anchor HR-TIME and RESOURCE-TIMING terms

- fetch.bs
This is a companion change to https://github.com/whatwg/html/pull/6677, which moves referrer policy into the policy container.
As a consequence of this change, the referrer policy used for the request is a snapshot of the relevant referrer policy when the request is being created, and won't change during the lifetime of the request, addressing a variant of https://github.com/whatwg/fetch/issues/832 for referrer policy.
***
<a href="https://whatpr.org/fetch/1233.html" title="Last updated on May 17, 2021, 8:44 AM UTC (c08fa08)">Preview</a> | <a href="https://whatpr.org/fetch/1233/3c0dd16...c08fa08.html" title="Last updated on May 17, 2021, 8:44 AM UTC (c08fa08)">Diff</a>
> Use referrer policy from policy container

- fetch.bs
CC @ricea, @youennf, @annevk 
Taking out our imperfect ban hammer again.
In the light of the recently published [ALPACA attack](https://alpaca-attack.com/), it might be worthwhile disallowing ports 989 and 990. We consider this the least controversial ports to add to the list, given they are assigned and below 1024.
One could also block port 2525, but that's... trickier?
Would be great if you,  @ricea, could help us gather some numbers.
I know Microsoft did _something_ in https://msrc.microsoft.com/update-guide/vulnerability/CVE-2021-31971 and Chromium was considering something in https://bugs.chromium.org/p/chromium/issues/detail?id=1197149
* Mozilla
* Chromium
* https://github.com/web-platform-tests/wpt/pull/29343
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1197149 …
> Block port 989, 990 (ftps-data and ftp)

- fetch.bs
In particular, define resolving domains and allow connection creation to be a race.
As a result this also inlines some of the time capture moments to be directly inside the obtain a connection algorithm.
This helps with #1243.
***
<a href="https://whatpr.org/fetch/1245.html" title="Last updated on Jun 14, 2021, 3:06 PM UTC (df2a2c0)">Preview</a> | <a href="https://whatpr.org/fetch/1245/43a0c94...df2a2c0.html" title="Last updated on Jun 14, 2021, 3:06 PM UTC (df2a2c0)">Diff</a>
> Elaborate on obtaining a connection

- fetch.bs
This patch incorporates draft-ietf-dnsop-let-localhost-be-localhost's recommendation
to hard-code resolution of `*.localhost` domains to 127.0.0.1 and [::1], matching
the existing behavior of both Chrome and Firefox. This change allows user agents
to ensure that localhost contexts meet the secure context requirements laid out
in https://w3c.github.io/webappsec-secure-contexts/#localhost.
See https://datatracker.ietf.org/doc/html/draft-ietf-dnsop-let-localhost-be-localhost
for additional detail and justification.
* Chrome ships this mapping.
* Firefox does as well.
* I don't think we can test this via WPT, as we can't ensure that a server is running on loopback addresses on the machine from which tests are being executed.
* Chrome: https://crbug.com/691930
* Firefox: …
> Hard-code `localhost` to loopback addresses.

- fetch.bs
This is a PR to fix the build now that in html embedder policy moved into the policy container (https://github.com/whatwg/html/pull/6793).
This replaces https://github.com/whatwg/fetch/pull/1258.
***
<a href="https://whatpr.org/fetch/1264.html" title="Last updated on Jul 2, 2021, 7:21 AM UTC (63c07ee)">Preview</a> | <a href="https://whatpr.org/fetch/1264/0cee83d...63c07ee.html" title="Last updated on Jul 2, 2021, 7:21 AM UTC (63c07ee)">Diff</a>
> Fix build with embedder policy in policy container

- fetch.bs
This uses some of the language added to #1244 but ports it to "obtain a connection" instead. The one thing that's missing a bit is how _proxy_ is supposed to be used. @ricea can you help with that?
@yutakahirano this also includes your suggested change to the "obtain a connection" parameters by merging _forceNew_ and _dedicated_.
***
<a href="https://whatpr.org/fetch/1259.html" title="Last updated on Jul 19, 2021, 5:37 PM UTC (29c7bda)">Preview</a> | <a href="https://whatpr.org/fetch/1259/613aad9...29c7bda.html" title="Last updated on Jul 19, 2021, 5:37 PM UTC (29c7bda)">Diff</a>
> Add proxy support to obtain a connection

- fetch.bs
This is needed for https://github.com/whatwg/html/issues/7104
and later on for https://github.com/whatwg/fetch/issues/1215.
Navigation timing reports the timing info from the HTML spec,
so it needs a mechanism to obfuscate the internals. So far that
obfuscation was internal to fetch and was done upon reporting.
***
<a href="https://whatpr.org/fetch/1309.html" title="Last updated on Sep 28, 2021, 2:33 PM UTC (d6889b0)">Preview</a> | <a href="https://whatpr.org/fetch/1309/b2f04e2...d6889b0.html" title="Last updated on Sep 28, 2021, 2:33 PM UTC (d6889b0)">Diff</a>
> Expose a mechanism for hiding internal timing info

- fetch.bs
Fixes #1310.
* Chromium
* Mozilla
* https://github.com/web-platform-tests/wpt/pull/31058
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1255711
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1733981
* Safari: https://bugs.webkit.org/show_bug.cgi?id=231174
***
<a href="https://whatpr.org/fetch/1312.html" title="Last updated on Oct 4, 2021, 4:11 PM UTC (ed0a9ca)">Preview</a> | <a href="https://whatpr.org/fetch/1312/b2f04e2...ed0a9ca.html" title="Last updated on Oct 4, 2021, 4:11 PM UTC (ed0a9ca)">Diff</a>
> Allow range header without preflight

- fetch.bs
Originally described in: https://github.com/mikewest/credentiallessness
`credentialless` and `require-corp` are similar. One or the other is a requirements for the `window.crossOriginIsolated` capability.
They differ mostly in the fetch specification. `require-corp` requires a CORP header for cross-origin no-cors responses. `credentialless` doesn't, but omits credentials (Cookies, clients certificates, etc...) in the request.
* HTML (https://github.com/whatwg/html/pull/6638)
* Define how to parse the `credentialless` value.
* From the HTML spec point of view, `credentialless` and `require-corp` are equivalent. They have been grouped into `compatible with cross-origin isolation` and the HTML spec rewritten to use this concept.
* Fetch: (https://github.com/whatwg/fetch/pull/1229)
* Define …
> Specify the behavior of `COEP: credentialless`,

- fetch.bs
Follow-up: integrating abort reason is #1343.
Fixes #1349.
***
<a href="https://whatpr.org/fetch/1353.html" title="Last updated on Nov 9, 2021, 12:31 PM UTC (9365d69)">Preview</a> | <a href="https://whatpr.org/fetch/1353/0613515...9365d69.html" title="Last updated on Nov 9, 2021, 12:31 PM UTC (9365d69)">Diff</a>
> Editorial: use AbortSignal's aborted predicate

- fetch.bs
* Should be a no-op without behavioral changes.
* Should be a no-op without behavioral changes.
* Chrome: …
* Firefox: …
* Safari: …
***
<a href="https://whatpr.org/fetch/1357.html" title="Last updated on Nov 18, 2021, 12:00 PM UTC (d2392ee)">Preview</a> | <a href="https://whatpr.org/fetch/1357/3ecab20...d2392ee.html" title="Last updated on Nov 18, 2021, 12:00 PM UTC (d2392ee)">Diff</a>
> Remove 'tainted origin flag'. (#1335)

- fetch.bs
This helped me understand a bit better what is going on in https://github.com/whatwg/html/pull/7260#discussion_r754639424
***
<a href="https://whatpr.org/fetch/1360.html" title="Last updated on Nov 29, 2021, 4:02 PM UTC (dcdf66a)">Preview</a> | <a href="https://whatpr.org/fetch/1360/5dc54a7...dcdf66a.html" title="Last updated on Nov 29, 2021, 4:02 PM UTC (dcdf66a)">Diff</a>
> Expand on processResponseEndOfBody values

- fetch.bs
Remove more instances where a concept member is used as a type.
***
<a href="https://whatpr.org/fetch/1361.html" title="Last updated on Nov 29, 2021, 9:41 AM UTC (837a840)">Preview</a> | <a href="https://whatpr.org/fetch/1361/5dc54a7...837a840.html" title="Last updated on Nov 29, 2021, 9:41 AM UTC (837a840)">Diff</a>
> Editorial: scheme is not a standalone type

- fetch.bs
It moved from XMLHttpRequest to HTML.
---
It seems this broke the build.
***
<a href="https://whatpr.org/fetch/1364.html" title="Last updated on Dec 2, 2021, 10:31 AM UTC (cc9738d)">Preview</a> | <a href="https://whatpr.org/fetch/1364/8e4553b...cc9738d.html" title="Last updated on Dec 2, 2021, 10:31 AM UTC (cc9738d)">Diff</a>
> Editorial: use HTML's definition of entry

- fetch.bs
The timing info attached to a network error is always "opaque",
containing only start/end time and the original request URL.
This change currently only applies to the fetch API, and should be
applied to the different callers of FETCCH as part of [this](whatwg/html#6542) and [this](whatwg/xhr#319) work.
Closes #1215
- [x ] At least two implementers are interested (and none opposed):
* See discussion at #1215.
* Currently WIP, see https://github.com/web-platform-tests/wpt/issues/30968
* Chrome: …
* Firefox: …
* Safari: https://bugs.webkit.org/show_bug.cgi?id=193902
***
<a href="https://whatpr.org/fetch/1311.html" title="Last updated on Dec 13, 2021, 12:17 PM UTC (78010e3)">Preview</a> | <a …
> Attach timing info and URL to network errors, and report for fetch API

- fetch.bs
@noamr could you review this as well?
***
<a href="https://whatpr.org/fetch/1370.html" title="Last updated on Dec 13, 2021, 12:44 PM UTC (de109f3)">Preview</a> | <a href="https://whatpr.org/fetch/1370/ed6221d...de109f3.html" title="Last updated on Dec 13, 2021, 12:44 PM UTC (de109f3)">Diff</a>
> Editorial: a network error's body is always null

- fetch.bs
In particular, this renames processResponseEndOfBody/process response end-of-body to processResponseConsumeBody/process response consume body and processResponseDone/process response done to processResponseEndOfBody/process response end-of-body.
Apologies for the confusion this may cause.
---
@noamr I went for these names after all as "end-of-body" seemed clearer than "flush" in relation to "response". (If using "flush" we'd have to rename "process request end-of-body" as well.)
***
<a href="https://whatpr.org/fetch/1369.html" title="Last updated on Dec 13, 2021, 12:40 PM UTC (4e7b983)">Preview</a> | <a href="https://whatpr.org/fetch/1369/ed6221d...4e7b983.html" title="Last updated on Dec 13, 2021, 12:40 PM UTC (4e7b983)">Diff</a>
> Rename response processing algorithms

- fetch.bs
This will be cleaned up in #1366.
***
<a href="https://whatpr.org/fetch/1377.html" title="Last updated on Dec 20, 2021, 7:48 AM UTC (378ff36)">Preview</a> | <a href="https://whatpr.org/fetch/1377/573df55...378ff36.html" title="Last updated on Dec 20, 2021, 7:48 AM UTC (378ff36)">Diff</a>
> Meta: fix breakage due to WebSockets

- fetch.bs
Before any particular fetch steps are performed, see if there is a
matching request already in the preload store and consume it.
This is called from the main fetch to avoid race conditions.
Depends on https://github.com/whatwg/html/pull/7260, and together they fix https://github.com/whatwg/fetch/issues/590.
* …
* …
- [x ] [Tests](https://github.com/web-platform-tests/wpt) are written and can be reviewed and commented upon at:
* https://github.com/web-platform-tests/wpt/pull/31539
* Chrome: …
* Firefox: …
* Safari: …
***
<a href="https://whatpr.org/fetch/1342.html" title="Last updated on Dec 13, 2021, 11:47 AM UTC (4c66e58)">Preview</a> | <a …
> Integration with preload

- fetch.bs
Use the controller for external timing reporting and aborts.
This allows removing the 1:1 dependency between timing info and a response, as a response can be shared across fetch
instances (e.g. when restoring a response from cache, or when forwarding a response through a service worker).
See https://github.com/whatwg/fetch/issues/1208
* Should reflect current implementation.
* …
* Chrome: …
* Firefox: …
* Safari: …
***
<a href="https://whatpr.org/fetch/1329.html" title="Last updated on Mar 11, 2022, 10:12 AM UTC (dc7f07c)">Preview</a> | <a href="https://whatpr.org/fetch/1329/435c5ec...dc7f07c.html" title="Last updated on Mar 11, 2022, 10:12 AM UTC (dc7f07c)">Diff</a>
> Return a "controller" instance from fetch

- fetch.bs
Closes https://github.com/whatwg/html/issues/7686
* Implemented in WebKit & Chromiun
* https://github.com/web-platform-tests/wpt/pull/33109
* https://github.com/web-platform-tests/wpt/pull/33205
* Chrome: N/A
* Firefox: [1759002](https://bugzilla.mozilla.org/show_bug.cgi?id=1759002)
* Safari: [238019](https://bugs.webkit.org/show_bug.cgi?id=238019)
***
<a href="https://whatpr.org/fetch/1411.html" title="Last updated on Mar 17, 2022, 1:07 PM UTC (808cb65)">Preview</a> | <a href="https://whatpr.org/fetch/1411/4561d5f...808cb65.html" title="Last updated on Mar 17, 2022, 1:07 PM UTC (808cb65)">Diff</a>
> Perform a CSP check when consuming preloaded response

- fetch.bs
Closes #1419
* …
* …
* …
* Chrome: …
* Firefox: …
* Safari: …
***
<a href="https://whatpr.org/fetch/1423.html" title="Last updated on Apr 5, 2022, 2:45 PM UTC (32e15f3)">Preview</a> | <a href="https://whatpr.org/fetch/1423/92b3578...32e15f3.html" title="Last updated on Apr 5, 2022, 2:45 PM UTC (32e15f3)">Diff</a>
> Editorial: Rename 'fetch finale' to 'fetch response handover'

- fetch.bs
Plumb an algorithm to process 103 Early Hints responses. The
algorithm is optional.
See https://github.com/whatwg/html/issues/7598 for the overall approach.
---
* Chromium
* Firefox
* https://github.com/web-platform-tests/wpt/tree/master/loading/early-hints
* Chrome: https://crbug.com/671310
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1407355
* Safari: https://bugs.webkit.org/show_bug.cgi?id=238921
* Deno (not for CORS changes): N/A
***
<a href="https://whatpr.org/fetch/1404.html" title="Last updated on Apr 7, 2022, 6:35 AM UTC (eda2b8d)">Preview</a> | <a href="https://whatpr.org/fetch/1404/8ebf2fd...eda2b8d.html" title="Last updated on Apr 7, 2022, 6:35 AM UTC (eda2b8d)">Diff</a>
> Process 103 Early Hints response

- fetch.bs
- `secure connection start` is identical to `connection start`
(TLS and connecting are part of the same flow in HTTP/3)
- `connection end` is right after the handshake
This corresponds to current Chromium implementation.
Closes https://github.com/w3c/navigation-timing/issues/165
* …
* …
* Currently WPT doesn't have support for H3 (except for `WebTransport`, TBD)
* Chrome: …
* Firefox: …
* Safari: …
***
<a href="https://whatpr.org/fetch/1417.html" title="Last updated on Apr 6, 2022, 10:54 AM UTC (50514eb)">Preview</a> | <a href="https://whatpr.org/fetch/1417/92b3578...50514eb.html" title="Last updated on Apr 6, 2022, 10:54 AM UTC (50514eb)">Diff</a>
> Specify connection timing for HTTP/3

- fetch.bs
Closes #1315
Adding some vague mostly-implementation-defined language to acknowledge that scheme upgrade can occur, similarly to HSTS, on discovery of a DNS HTTPS RR.  Also added a (similarly vague and implementation-defined) note that origin resolution might query DNS for HTTPS and return more than addresses.
***
<a href="https://whatpr.org/fetch/1325.html" title="Last updated on Oct 11, 2021, 6:12 PM UTC (38a35c3)">Preview</a> | <a href="https://whatpr.org/fetch/1325/6f37b51...38a35c3.html" title="Last updated on Oct 11, 2021, 6:12 PM UTC (38a35c3)">Diff</a>
***
<a href="https://whatpr.org/fetch/1325.html" title="Last updated on Apr 7, 2022, 6:23 PM UTC (9e2c56d)">Preview</a> | <a href="https://whatpr.org/fetch/1325/8ebf2fd...9e2c56d.html" title="Last updated on Apr 7, 2022, 6:23 PM UTC …
> Acknowledge interaction with draft-ietf-dnsop-svcb-https scheme redirect

- fetch.bs
Will be used by https://github.com/w3c/server-timing/pull/87
Decode and split `Server-Timing` headers, and append the raw headers to the `fetch timing info`. The server timing spec would later parse these headers and expose them.
* Already implemented
* Rigorously tested in https://github.com/web-platform-tests/wpt/tree/master/server-timing
* N/a
***
<a href="https://whatpr.org/fetch/1406.html" title="Last updated on Apr 20, 2022, 11:33 AM UTC (6d47c8f)">Preview</a> | <a href="https://whatpr.org/fetch/1406/3a65729...6d47c8f.html" title="Last updated on Apr 20, 2022, 11:33 AM UTC (6d47c8f)">Diff</a>
> Add server-timing to timing info struct

- fetch.bs
Closes https://github.com/whatwg/fetch/issues/1221
Closes https://github.com/whatwg/fetch/issues/1421
* Already implemented, it's an implemented piece that was missing in the spec.
* Existing tests: https://wpt.fyi/results/resource-timing/cross-origin-iframe.html?label=experimental&label=master&aligned
* N/A
***
<a href="https://whatpr.org/fetch/1422.html" title="Last updated on Apr 28, 2022, 7:03 AM UTC (67fbcc2)">Preview</a> | <a href="https://whatpr.org/fetch/1422/14898c0...67fbcc2.html" title="Last updated on Apr 28, 2022, 7:03 AM UTC (67fbcc2)">Diff</a>
> Perform TAO check for nested navigations

- fetch.bs
Document the need to return a network error on fetch if the blob URL has
no backing blob.
* …
* …
* https://github.com/web-platform-tests/wpt/pull/33941
* Chrome: …
* Firefox: …
* Safari: …
Fixes: https://github.com/whatwg/fetch/issues/1077
***
<a href="https://whatpr.org/fetch/1435.html" title="Last updated on May 13, 2022, 1:13 PM UTC (3fccfa7)">Preview</a> | <a href="https://whatpr.org/fetch/1435/3ab5102...3fccfa7.html" title="Last updated on May 13, 2022, 1:13 PM UTC (3fccfa7)">Diff</a>
> Only allow blob: URLs that have a backing blob

- fetch.bs
This commit adds a `Response.json` static method that can be used to
create well formed JSON responses will very little effort.
The JSON response is _not_ pretty printed.
Closes #1389
---
* [Chrome](https://github.com/whatwg/fetch/pull/1392#issuecomment-1123133441)
* [Firefox](https://github.com/whatwg/fetch/pull/1392#pullrequestreview-970555855)
* Deno
* Cloudflare Workers
* https://github.com/web-platform-tests/wpt/pull/32825
* Chrome: https://crbug.com/1305358
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1758943
* Safari: https://bugs.webkit.org/show_bug.cgi?id=240375
* Deno: https://github.com/denoland/deno/issues/13902
***
<a href="https://whatpr.org/fetch/1392.html" title="Last updated on May 13, 2022, 9:02 AM UTC (7ef2f43)">Preview</a> | <a …
> Add `Response.json` static method

- fetch.bs
Fixes #1433. The HTML-side counterpart is whatwg/html#7885.
This is also a minor follow-up of whatwg/html#7474.
* See whatwg/html#7474
* The render-blocking flag itself is not web-exposed and can't be tested against with WPT
* The flag may affect [priority](https://fetch.spec.whatwg.org/#concept-request-priority), which is a UA-defined object and cannot be tested against with WPT, either.
* Blink-specific tests are at https://chromium-review.googlesource.com/c/chromium/src/+/3627294
* See whatwg/html#7474
***
<a href="https://whatpr.org/fetch/1432.html" title="Last updated on May 23, 2022, 9:12 PM UTC (96a7020)">Preview</a> | <a href="https://whatpr.org/fetch/1432/a15074d...96a7020.html" …
> Add a render-blocking boolean flag to the request concept

- fetch.bs
It's not implemented as specified and only has one interested implementer.
* …
* …
* …
* Chrome: …
* Firefox: …
* Safari: …
***
<a href="https://whatpr.org/fetch/1441.html" title="Last updated on May 16, 2022, 8:46 AM UTC (c4532ce)">Preview</a> | <a href="https://whatpr.org/fetch/1441/03c041e...c4532ce.html" title="Last updated on May 16, 2022, 8:46 AM UTC (c4532ce)">Diff</a>
> Remove CORB

- fetch.bs
While working on ORB I noticed that the existing text had a number of minor mistakes.
cc @MattiasBuelens
***
<a href="https://whatpr.org/fetch/1445.html" title="Last updated on May 30, 2022, 12:02 PM UTC (83e05e8)">Preview</a> | <a href="https://whatpr.org/fetch/1445/78f9bdd...83e05e8.html" title="Last updated on May 30, 2022, 12:02 PM UTC (83e05e8)">Diff</a>
> Correct and consistify TransformStream boilerplate

- fetch.bs
This is useful for HTML's fetch a classic script and Fetch's upcoming opaque-response blocking. It will also be useful to more tightly define equivalent legacy setups elsewhere.
***
<a href="https://whatpr.org/fetch/1447.html" title="Last updated on Jun 1, 2022, 4:31 PM UTC (5d92f26)">Preview</a> | <a href="https://whatpr.org/fetch/1447/4128e96...5d92f26.html" title="Last updated on Jun 1, 2022, 4:31 PM UTC (5d92f26)">Diff</a>
> Add algorithm to extract an encoding from a MIME type

- fetch.bs
The new HTTP-SEMANTICS spec (https://www.rfc-editor.org/info/rfc9110)
obsoletes several other RFCs that are referenced from the Fetch spec.
Updated all of those refs to use HTTP-SEMANTICS.
* …
* …
* …
* Chrome: …
* Firefox: …
* Safari: …
***
<a href="https://whatpr.org/fetch/1451.html" title="Last updated on Jun 8, 2022, 1:17 PM UTC (65b28d0)">Preview</a> | <a href="https://whatpr.org/fetch/1451/82bb961...65b28d0.html" title="Last updated on Jun 8, 2022, 1:17 PM UTC (65b28d0)">Diff</a>
> Editorial: Update severals biblio refs to HTTP-SEMANTICS

- fetch.bs
This is to reduce the risk to break existing HTTP/1.1 servers.
See #966, #1438.
* …
* …
* …
* Chrome: …
* Firefox: …
* Safari: …
***
<a href="https://whatpr.org/fetch/1444.html" title="Last updated on Jun 16, 2022, 8:12 AM UTC (829c52e)">Preview</a> | <a href="https://whatpr.org/fetch/1444/78f9bdd...829c52e.html" title="Last updated on Jun 16, 2022, 8:12 AM UTC (829c52e)">Diff</a>
> Disallow streaming upload on HTTP/1.1 connections

- fetch.bs
Closes https://github.com/whatwg/fetch/issues/1208
Closes https://github.com/w3c/navigation-timing/pull/131
A new method called `conclude` reports the timing for the resource.
The timing info used is the one attached to the fetch rather than
one attached to a response.
This is done to reduce ambiguities when timing info is attached to
the `response`, as it's unclear what happens to that timing info
when a response is cloned, reused, serialized or stored & restored
from cache.
Call-site patches:
Update resource/navigation to use `conclude` / `resource-info`: https://github.com/whatwg/html/pull/7722
Update XHR to use `conclude`: https://github.com/whatwg/xhr/pull/347
Update CSS to use `conclude`: https://github.com/w3c/csswg-drafts/pull/7355
Update beacon to use `conclude`: …
> Call `finalize and report timing` automatically on end-of-body

- fetch.bs
Introduce the member, and throw if init.duplex is not set in the
Request constructor, as discussed at #1438.
* Chrome
* Mozilla
* Deno
* https://github.com/web-platform-tests/wpt/pull/34496
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1337696
* Firefox: This is a part of the streaming upload feature.
* Safari: This is a part of the streaming upload feature.
* Deno (not for CORS changes): This is a part of the streaming upload feature.
***
<a href="https://whatpr.org/fetch/1457.html" title="Last updated on Jul 1, 2022, 8:09 AM UTC (557f24d)">Preview</a> | <a href="https://whatpr.org/fetch/1457/4c93f89...557f24d.html" title="Last updated on Jul 1, 2022, 8:09 AM UTC …
> Introduce RequestInit.duplex

- fetch.bs
The note is about service workers.
* …
* …
* …
* Chrome: …
* Firefox: …
* Safari: …
***
<a href="https://whatpr.org/fetch/1467.html" title="Last updated on Jul 8, 2022, 7:54 AM UTC (326250f)">Preview</a> | <a href="https://whatpr.org/fetch/1467/edf07e5...326250f.html" title="Last updated on Jul 8, 2022, 7:54 AM UTC (326250f)">Diff</a>
> Editorial: Move initiator type to other side of note

- fetch.bs
Currently, 103 code is a [`null body status`](https://fetch.spec.whatwg.org/#null-body-status).
A note in Step 6 of [`initialize a response`](https://fetch.spec.whatwg.org/#initialize-a-response) mentions only 101.
103 is also an exception ∵ it's filtered out by Step 1.
***
<a href="https://whatpr.org/whatwg-fetch/1465.html" title="Last updated on Jul 28, 2022, 6:36 AM UTC (7cb9898)">Preview</a> | <a href="https://whatpr.org/fetch/1465/50d77e6...7cb9898.html" title="Last updated on Jul 28, 2022, 6:36 AM UTC (7cb9898)">Diff</a>
> Editorial: Add 103 to note about null body Response

- fetch.bs
These changes are to support addition of a render blocking status field to Perfomance resource timing. Further details are available at https://github.com/w3c/resource-timing/pull/327
~~For HTML side changes see https://github.com/whatwg/html/pull/7979~~
* Chromium : https://chromestatus.com/feature/5166965277589504
* Firefox : https://github.com/mozilla/standards-positions/issues/662#issuecomment-1171568555
* https://chromium-review.googlesource.com/c/chromium/src/+/3709521
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1337256
* Firefox: …
* Safari: …
***
<a href="https://whatpr.org/fetch/1449.html" title="Last updated on Jul 28, 2022, 3:12 PM …
> Add render-blocking boolean to fetch timing info

- fetch.bs
w3c/reporting#253 changed which algorithm is exported. The build will get fixed once Shepherd picks up that change.
I'm pretty sure this is the right algorithm to call, but please double check
that these should actually be sent to the network.
* …
* …
* …
* Chrome: …
* Firefox: …
* Safari: …
***
<a href="https://whatpr.org/fetch/1487.html" title="Last updated on Sep 22, 2022, 9:56 AM UTC (81bec05)">Preview</a> | <a href="https://whatpr.org/fetch/1487/9bb2ded...81bec05.html" title="Last updated on Sep 22, 2022, 9:56 AM UTC (81bec05)">Diff</a>
> Fix the reference to "generate and queue a report".

- fetch.bs
Also document how we should refactor this in the future.
Tests: https://wpt.fyi/fetch/security/1xx-response.any.html.
Fixes #1397.
Checkboxes are not applicable as this is already implemented as such as I understand it.
* …
* …
* …
* Chrome: …
* Firefox: …
* Safari: …
***
<a href="https://whatpr.org/fetch/1491.html" title="Last updated on Sep 22, 2022, 10:08 AM UTC (c245ee4)">Preview</a> | <a href="https://whatpr.org/fetch/1491/0d95632...c245ee4.html" title="Last updated on Sep 22, 2022, 10:08 AM UTC (c245ee4)">Diff</a>
> Only break for 101 in "websocket" mode

- fetch.bs
***
<a href="https://whatpr.org/fetch/1494.html" title="Last updated on Sep 24, 2022, 8:50 PM UTC (5bf3b6c)">Preview</a> | <a href="https://whatpr.org/fetch/1494/0d95632...5bf3b6c.html" title="Last updated on Sep 24, 2022, 8:50 PM UTC (5bf3b6c)">Diff</a>
> Editorial: Fix incorrect variable name in 'create a Request object'

- fetch.bs
Add support for parsing a range header in the suffix byte range spec
form.
* …
* …
* Partially [here](https://github.com/web-platform-tests/wpt/pull/34384#discussion_r898469534)
* Chrome: …
* Firefox: …
* Safari: …
***
<a href="https://whatpr.org/fetch/1454.html" title="Last updated on Sep 23, 2022, 4:36 PM UTC (3ebbb33)">Preview</a> | <a href="https://whatpr.org/fetch/1454/0d95632...3ebbb33.html" title="Last updated on Sep 23, 2022, 4:36 PM UTC (3ebbb33)">Diff</a>
> Add support for parsing a suffix byte range spec

- fetch.bs
We think it makes sense to define a destination type specific to FedCM requests (https://fedidcg.github.io/FedCM/)
This would replace the Sec-FedCM-CSRF header that is currently in the FedCM spec.
* Chrome is interested (we're the ones proposing this)
* Firefox is interested in FedCM [in general](https://mozilla.github.io/standards-positions/#fedcm) and has also suggested a change along these lines (https://github.com/fedidcg/FedCM/issues/320, though that issue is kind of meandering and has morphed into general CORS discussions)
* I will add WPT tests once I update Chrome's implementation to use this destination
* Chrome: https://crbug.com/1368382
* Firefox: n/a, fedcm impl still in progress
* Safari: n/a, does not support fedcm
* Deno (not for CORS changes): n/a
(See [WHATWG Working …
> Add a destination type for FedCM

- fetch.bs
#1022 We need to send the Origin header for same-origin CORS requests even with no-referrer. This is the current behavior of all browsers (https://wpt.fyi/results/fetch/origin/assorted.window.html?label=master&label=experimental&aligned) and not doing so [breaks the web](https://bugzilla.mozilla.org/show_bug.cgi?id=1775235).
* Firefox is interested
* Existing behavior in Safari and Chrome (which diverges further)
* fetch/origin/assorted.window.html needs to be updated ("Origin header and POST same-origin fetch cors mode with Referrer-Policy no-referrer")
* Chrome: Existing behavior
* Firefox: (Re)-Implemented in https://bugzilla.mozilla.org/show_bug.cgi?id=1775235
* Safari: Existing behavior
(See [WHATWG Working Mode: …
> Always send Origin header for (non HEAD/GET) CORS requests

- fetch.bs
As per #1450 the intent was never to allow this. The algorithm before #1454 would yield undefined behavior for this input, but after it ended up being allowed. This change makes it clearly disallowed.
* …
* …
* …
* Chrome: …
* Firefox: …
* Safari: …
***
<a href="https://whatpr.org/fetch/1501.html" title="Last updated on Oct 12, 2022, 2:45 PM UTC (9013d5c)">Preview</a> | <a href="https://whatpr.org/fetch/1501/283c2ae...9013d5c.html" title="Last updated on Oct 12, 2022, 2:45 PM UTC (9013d5c)">Diff</a>
> Do not CORS-safelist a Range header without a start

- fetch.bs
Remove the existing navigation redirect, and allow the caller
to use the controller to continue to the next redirect.
This simplifies the navigation HTML<->FETCH flow, as now there is
a single `fetch params` struct for the course of the entire navigation.
Up until now some data from fetch params would be lost, like timing info
and task desination, because navigation fetches create a brand new
`fetch params` struct. Now that data is retained, and the only thing that
HTML needs to do is call `process the next redirect` on the fetch controller.
* …
* …
* …
* Chrome: …
* Firefox: …
* Safari: …
***
<a href="https://whatpr.org/fetch/1469.html" title="Last updated on …
> Editorial: Use controller for navigation redirect

- fetch.bs
***
<a href="https://whatpr.org/fetch/1502.html" title="Last updated on Oct 14, 2022, 8:39 AM UTC (f3173aa)">Preview</a> | <a href="https://whatpr.org/fetch/1502/8023bd0...f3173aa.html" title="Last updated on Oct 14, 2022, 8:39 AM UTC (f3173aa)">Diff</a>
> Editorial: Fix typo in 'fetch response handover'

- fetch.bs
Helps with https://github.com/whatwg/fetch/issues/1504.
***
<a href="https://whatpr.org/fetch/1505.html" title="Last updated on Oct 20, 2022, 3:25 PM UTC (1322132)">Preview</a> | <a href="https://whatpr.org/fetch/1505/e5f025a...1322132.html" title="Last updated on Oct 20, 2022, 3:25 PM UTC (1322132)">Diff</a>
> Ensure scheme fetch always returns a response with an actual body

- fetch.bs
This depends on https://github.com/w3c/FileAPI/pull/182.
Together with #1505 this fixes #1504.
***
<a href="https://whatpr.org/fetch/1506.html" title="Last updated on Oct 20, 2022, 3:44 PM UTC (599ebef)">Preview</a> | <a href="https://whatpr.org/fetch/1506/e5f025a...599ebef.html" title="Last updated on Oct 20, 2022, 3:44 PM UTC (599ebef)">Diff</a>
> Actually define Blob-to-ReadableStream conversion

- fetch.bs
It doesn't save a whole lot of text, but maybe this is good? Or were you thinking of a response constructor type of thing?
***
<a href="https://whatpr.org/fetch/1507.html" title="Last updated on Oct 21, 2022, 9:05 AM UTC (89fb617)">Preview</a> | <a href="https://whatpr.org/fetch/1507/4cd70cf...89fb617.html" title="Last updated on Oct 21, 2022, 9:05 AM UTC (89fb617)">Diff</a>
> Editorial: introduce "convert" operation for byte-sequence to body

- fetch.bs
These changes are to support addition of http response status code to Perfomance resource timing. Further details are available at https://github.com/w3c/resource-timing/pull/335
* Chromium : https://chromestatus.com/feature/5163838794629120
* Firefox : https://github.com/mozilla/standards-positions/issues/665
* https://chromium-review.googlesource.com/c/chromium/src/+/3754923
* https://chromium-review.googlesource.com/c/chromium/src/+/3958184
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1343293
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1796785
* Safari: https://bugs.webkit.org/show_bug.cgi?id=246857
***
<a …
> Pass in response status to mark resource timing

- fetch.bs
This was overlooked in https://github.com/whatwg/fetch/commit/cbca2c2f3a37084e336e14348de683f8ffa0fed9 and is already handled by HTTP-network-or-cache fetch.
Also remove the "abort when" wrapper as this can all be done synchronously. If the fetch is canceled it's caught immediately after.
And finally use the tracking-vector feature instead of a note.
***
<a href="https://whatpr.org/fetch/1508.html" title="Last updated on Oct 21, 2022, 12:36 PM UTC (53a367e)">Preview</a> | <a href="https://whatpr.org/fetch/1508/4a7bf35...53a367e.html" title="Last updated on Oct 21, 2022, 12:36 PM UTC (53a367e)">Diff</a>
> Remove HTTP cache talk in HTTP-network fetch

- fetch.bs
Fixes #1509. Follow-ups: #1511 & #1512.
***
<a href="https://whatpr.org/fetch/1513.html" title="Last updated on Oct 25, 2022, 8:44 AM UTC (9f5e5c4)">Preview</a> | <a href="https://whatpr.org/fetch/1513/6291752...9f5e5c4.html" title="Last updated on Oct 25, 2022, 8:44 AM UTC (9f5e5c4)">Diff</a>
> Describe filtered responses better

- fetch.bs
No longer use "abort when" for blob: URLs as all the handling is synchronous anyway.
Capture aborting that might have happened between fetch going in parallel and scheme fetch getting invoked for all schemes.
***
<a href="https://whatpr.org/fetch/1515.html" title="Last updated on Oct 26, 2022, 7:22 AM UTC (b6af6ff)">Preview</a> | <a href="https://whatpr.org/fetch/1515/b56692a...b6af6ff.html" title="Last updated on Oct 26, 2022, 7:22 AM UTC (b6af6ff)">Diff</a>
> Refactor scheme fetch

- fetch.bs
Depends on https://github.com/whatwg/websockets/pull/36.
Co-Authored-By: Yutaka Hirano <yhirano@chromium.org>
***
<a href="https://whatpr.org/fetch/1516.html" title="Last updated on Oct 26, 2022, 9:11 AM UTC (3709ea4)">Preview</a> | <a href="https://whatpr.org/fetch/1516/b56692a...3709ea4.html" title="Last updated on Oct 26, 2022, 9:11 AM UTC (3709ea4)">Diff</a>
> Editorial: WebSockets has its own standard now

- fetch.bs
Follows https://github.com/whatwg/html/pull/6315. One reference remains to "target browsing context" which probably requires HTML-side updates first.
***
<a href="https://whatpr.org/fetch/1525.html" title="Last updated on Nov 2, 2022, 2:57 AM UTC (591d70b)">Preview</a> | <a href="https://whatpr.org/fetch/1525/1c3a3bb...591d70b.html" title="Last updated on Nov 2, 2022, 2:57 AM UTC (591d70b)">Diff</a>
> Update to use navigables instead of browsing contexts

- fetch.bs
This change makes several changes:
* Makes "get, decode, and split" callable with a value. This is generally not advisable so this is not exported.
* Generalizes forbidden header name to forbidden request-headers so it can target values for specific headers.
* Takes advantage of that for X-HTTP-Method, X-HTTP-Method-Override, and X-Method-Override.
Tests: WPT fetch/api/basic/request-forbidden-headers.any.js.
XHR PR: TODO.
* Already implemented.
* Already tested.
* Chromium: N/A
* Gecko: N/A
* WebKit: N/A
* Deno (not for CORS changes): N/A?
***
<a href="https://whatpr.org/fetch/1541.html" title="Last updated on Nov 23, 2022, 2:59 PM UTC (983dcd6)">Preview</a> | <a …
> Refactor forbidden request-headers

- fetch.bs
***
<a href="https://whatpr.org/fetch/1547.html" title="Last updated on Nov 23, 2022, 4:55 PM UTC (cd51409)">Preview</a> | <a href="https://whatpr.org/fetch/1547/92e6c91...cd51409.html" title="Last updated on Nov 23, 2022, 4:55 PM UTC (cd51409)">Diff</a>
> Parse a MIME type expects a string

- fetch.bs
The behavior defined here is such that if you go A1 -> B -> A2, A2 doesn't see the header. I think that's what we want. If you go A1 -> A2 -> B, B won't see the header. (A1 is making the initial request in both scenarios.)
Tests: ...
Fixes #944.
* WebKit
* Gecko
* Chromium
* https://github.com/web-platform-tests/wpt/pull/37145
* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1393520
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1802086
* WebKit: N/A
* Deno (not for CORS changes): https://github.com/denoland/deno/pull/16745
***
<a href="https://whatpr.org/fetch/1544.html" title="Last updated on Nov 25, 2022, 8:26 AM UTC (eaa1d3b)">Preview</a> | <a …
> Remove Authorization header upon cross-origin redirect

- fetch.bs
Add `<div algorithm>` wrappers to defined header algorithms.
Related to: https://github.com/whatwg/fetch/issues/1526
***
<a href="https://whatpr.org/fetch/1549.html" title="Last updated on Nov 24, 2022, 7:20 PM UTC (eb48da0)">Preview</a> | <a href="https://whatpr.org/fetch/1549/223ca89...eb48da0.html" title="Last updated on Nov 24, 2022, 7:20 PM UTC (eb48da0)">Diff</a>
> Editorial: add algorithm wrapper to header algorithms

- fetch.bs
This applies the [specified changes](https://wicg.github.io/priority-hints/#fetch-integration) from the [Priority Hints spec](https://wicg.github.io/priority-hints/) to fetch for [#1319](https://github.com/whatwg/fetch/issues/1319).
The main changes are:
* Rename the existing implementor-internal `priority` to `internal priority`.
* Add a new `priority` enum to the `Request` and `RequestInit` objects.
* Chrome (Shipped in 103)
* [Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1797715)
* https://github.com/web-platform-tests/wpt/blob/master/interfaces/priority-hints.idl
* https://github.com/web-platform-tests/wpt/blob/master/priority-hints/fetch-api-request.tentative.any.js
* https://github.com/web-platform-tests/wpt/blob/master/priority-hints/service-worker-fetch-request-priority.te …
> Add the Priority Hints changes to the fetch spec

- fetch.bs
* This was proposed originally as part of changes to MIX, which have since been implemented by Chrome and are in the process of being implemented by Firefox. Additionally Safari supported the MIX changes.
* Tests exist under https://github.com/web-platform-tests/wpt/tree/master/mixed-content/tentative/autoupgrades.
* Chromium: This behavior is already launched in Chrome
* Gecko: Unclear if bug exists yet, but it's planned for launching in Nightly soon (see discussion in web-platform-tests/wpt#37080)
***
<a href="https://whatpr.org/fetch/1578.html" title="Last updated on Dec 21, 2022, 1:11 AM UTC (1bce7f0)">Preview</a> | <a href="https://whatpr.org/fetch/1578/84ea7db...1bce7f0.html" title="Last …
> Add reference to MIX in main fetch

- fetch.bs
Following https://github.com/whatwg/streams/pull/1250
Closes #1568
* …
* …
* …
* Chromium: …
* Gecko: …
* WebKit: …
***
<a href="https://whatpr.org/fetch/1569.html" title="Last updated on Dec 22, 2022, 2:06 PM UTC (c6dc3a2)">Preview</a> | <a href="https://whatpr.org/fetch/1569/84ea7db...c6dc3a2.html" title="Last updated on Dec 22, 2022, 2:06 PM UTC (c6dc3a2)">Diff</a>
> Editorial: Amend body reading to use no-promise version

- fetch.bs
The `Server-Timing` header is protected by TAO, so there's no need to safelist it in CORS as well.
Closes #1511
* Already implemented
* https://github.com/web-platform-tests/wpt/pull/37714
* Already implemented
***
<a href="https://whatpr.org/fetch/1584.html" title="Last updated on Jan 3, 2023, 8:07 AM UTC (edff313)">Preview</a> | <a href="https://whatpr.org/fetch/1584/464326e...edff313.html" title="Last updated on Jan 3, 2023, 8:07 AM UTC (edff313)">Diff</a>
> Use internal response for Server-Timing

- fetch.bs
Prolly best to wait and rebase this on top of #1556 once it lands.
***
<a href="https://whatpr.org/fetch/1561.html" title="Last updated on Jan 3, 2023, 9:17 AM UTC (f477029)">Preview</a> | <a href="https://whatpr.org/fetch/1561/f6e9b8d...f477029.html" title="Last updated on Jan 3, 2023, 9:17 AM UTC (f477029)">Diff</a>
> Editorial: clean up definitions of network errors

- fetch.bs
Accounting for RFC updates is really the most tedious nonsense. I'm glad we don't really have that cross-reference issue in the web platform anymore.
I still need to double check this, but it's a start. Fixup commits most welcome.
(I attempted to use the IETF URLs that I think we prefer. Can we document that policy somewhere?)
cc @dlrobertson @domenic
Fixes https://github.com/whatwg/fetch/issues/1558.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jan 10, 2023, 3:58 PM UTC)_.
<details>
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to …
> Editorial: account for HTTP updates

- fetch.bs
Send `Sec-Purpose: prefetch` for prefetch requests
The purpose headers allows servers to discern between regular requests
and "resource hints" - requests that are only meant to populate
caches.
This replaces the existing `Purpose` and `x-moz: prefetch` headers.
Closes w3c/webappsec-fetch-metadata#84
Closes https://github.com/w3c/resource-hints/issues/74
Part of whatwg/html#8111
* Chromium
* Apple: https://github.com/WebKit/standards-positions/issues/114
* https://github.com/mozilla/standards-positions/issues/723
* https://github.com/web-platform-tests/wpt/pull/35707
* Chrome: 
[1358419: `Sec-Purpose` header](https://bugs.chromium.org/p/chromium/issues/detail?id=1358419)
* Firefox: 
[1788167: Align prefetch with spec](https://bugzilla.mozilla.org/show_bug.cgi?id=1788167)
* Safari: …
> Send `Sec-Purpose: prefetch` header for prefetch requests

- fetch.bs
Together with https://github.com/whatwg/html/pull/8111
* Deferring to dicussion at https://github.com/whatwg/html/pull/8111
* https://github.com/web-platform-tests/wpt/pull/35707
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=626081
* Firefox: [1788167: Align prefetch with spec](https://bugzilla.mozilla.org/show_bug.cgi?id=1788167)
* Safari: https://bugs.webkit.org/show_bug.cgi?id=49238
* Deno (not for CORS changes): N/A
***
<a href="https://whatpr.org/fetch/1485.html" title="Last updated on Jan 16, 2023, 1:20 PM UTC (02e6fe0)">Preview</a> | <a href="https://whatpr.org/fetch/1485/62e5d0b...02e6fe0.html" title="Last updated on Jan 16, 2023, 1:20 PM UTC (02e6fe0)">Diff</a>
> Accept header for prefetch

- fetch.bs
encoded/decoded body size relate to the resource, not to the timing. Body size of cors-same-origin resources is anyway observable in service workers.
This is part of
https://github.com/w3c/resource-timing/issues/220#issuecomment-1177615190
* Chromium
* Gecko
* https://github.com/web-platform-tests/wpt/pull/37884
* https://github.com/web-platform-tests/wpt/pull/37257
* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1404669
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1811293
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=251144
***
<a href="https://whatpr.org/fetch/1556.html" title="Last updated on Jan 25, 2023, 12:57 PM UTC (9071708)">Preview</a> | <a …
> Body sizes should be CORS rather than TAO protected

- fetch.bs
The `prefetch-src` directive was [removed from CSP](https://github.com/w3c/webappsec-csp/pull/582). Instead we use either `default-src` or the least restrictive directive if one exists.
Updating the destination table to reflect this.
***
<a href="https://whatpr.org/fetch/1595.html" title="Last updated on Jan 25, 2023, 1:11 PM UTC (86af10f)">Preview</a> | <a href="https://whatpr.org/fetch/1595/a5560d2...86af10f.html" title="Last updated on Jan 25, 2023, 1:11 PM UTC (86af10f)">Diff</a>
> Editorial: Remove `prefetch-src`

- fetch.bs
Related to: #1526
***
<a href="https://whatpr.org/fetch/1596.html" title="Last updated on Jan 26, 2023, 2:20 PM UTC (8424848)">Preview</a> | <a href="https://whatpr.org/fetch/1596/a5560d2...8424848.html" title="Last updated on Jan 26, 2023, 2:20 PM UTC (8424848)">Diff</a>
> Editorial: add <div algorithm> wrappers to Header class

- fetch.bs
Fixes #267, paired with https://github.com/w3c/FileAPI/pull/188
The switch is quite simple it seems 👀
* Mozilla (already shipped)
* Google @ricea
* Apple? @annevk
* https://github.com/web-platform-tests/wpt/pull/37910
* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1243329
* Gecko: (Shipped)
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=250549
* Deno (not for CORS changes): https://github.com/denoland/deno/issues/17386
***
<a href="https://whatpr.org/fetch-1/1593.html" title="Last updated on Feb 17, 2023, 7:53 PM UTC (5473365)">Preview</a> | <a href="https://whatpr.org/fetch/1593/093c622...5473365.html" title="Last updated on Feb 17, 2023, 7:53 PM UTC (5473365)">Diff</a>
> Set body with byte reading support

- fetch.bs
Add HTTP optional white space handling to the single range header parser.
* …
* …
* https://github.com/web-platform-tests/wpt/pull/34384
* https://github.com/web-platform-tests/wpt/pull/37569
* Chromium: …
* Gecko: …
* WebKit: …
I didn't see a concrete consensus made about the CORS case in https://github.com/whatwg/fetch/issues/1070, so I went with the more conservative option here.
***
<a href="https://whatpr.org/fetch/1564.html" title="Last updated on Feb 16, 2023, 1:41 AM UTC (1be32b3)">Preview</a> | <a href="https://whatpr.org/fetch/1564/093c622...1be32b3.html" title="Last updated on Feb 16, 2023, 1:41 AM UTC (1be32b3)">Diff</a>
> Add HTTP OWS handling to single range header parsing

- fetch.bs
* Chromium and Webkit seem to have at least partial implementations
* https://github.com/web-platform-tests/wpt/pull/34384
* https://github.com/web-platform-tests/wpt/pull/37569
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1784880
* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1399678
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=248994
Implement support for blob range requests.
Related to: https://github.com/whatwg/fetch/issues/1070
***
<a href="https://whatpr.org/fetch/1520.html" title="Last updated on Feb 20, 2023, 9:14 AM UTC (e330519)">Preview</a> | <a href="https://whatpr.org/fetch/1520/f6e9b8d...e330519.html" title="Last updated on Feb 20, 2023, 9:14 AM …
> Add support for blob range requests

- fetch.bs
This intends to be a summary of informative notes in the #Requests section, into a concise "starter" guide to populating a request, which is usually the tricky bit of using Fetch.
Requested by authors of other specs, see for example: https://github.com/w3ctag/design-principles/issues/238 https://github.com/fedidcg/FedCM/issues/320
***
<a href="https://whatpr.org/fetch/1585.html" title="Last updated on Mar 2, 2023, 1:03 PM UTC (dd89623)">Preview</a> | <a href="https://whatpr.org/fetch/1585/a5560d2...dd89623.html" title="Last updated on Mar 2, 2023, 1:03 PM UTC (dd89623)">Diff</a>
> Editorial: Add prose about constructing a request

- fetch.bs
In particular:
* Return a network error when rangeStart is out-of-range.
* If rangeStart is null, it should become fullLength - rangeEnd, not 0. rangeEnd then has to be adjusted as well.
* If rangeEnd is out-of-range, it should become fullLength - 1.
Tests: ...
* Fixes for #1520.
* https://github.com/web-platform-tests/wpt/pull/39108
* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1399678
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1784880
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=248994
***
<a href="https://whatpr.org/fetch/1621.html" title="Last updated on Mar 23, 2023, 2:29 PM UTC (1bced79)">Preview</a> | <a …
> Correct blob: URL range requests

- fetch.bs
Fixes #1610
***
<a href="https://whatpr.org/fetch-1/1628.html" title="Last updated on Apr 5, 2023, 7:35 PM UTC (5d345ab)">Preview</a> | <a href="https://whatpr.org/fetch/1628/8f10983...5d345ab.html" title="Last updated on Apr 5, 2023, 7:35 PM UTC (5d345ab)">Diff</a>
> Editorial: Use "pull from bytes" algorithm

- fetch.bs
Rename the "extract-value flag" argument to the algorithm "collect an HTTP quoted string" to a boolean "extract-value" that will by default be false.
Fixes: #1567
***
<a href="https://whatpr.org/fetch/1641.html" title="Last updated on May 5, 2023, 9:40 PM UTC (ba2d76c)">Preview</a> | <a href="https://whatpr.org/fetch/1641/ca10f49...ba2d76c.html" title="Last updated on May 5, 2023, 9:40 PM UTC (ba2d76c)">Diff</a>
> Editorial: update args for collect an HTTP quoted string

- fetch.bs
See https://github.com/w3c/resource-timing/issues/345
Since early hints have landed, there are additional useful timestamp
that's currently not exposed:
- First interim response start (e.g. when we received a 103)
as a different timestamp from the final response start
(e.g. when we received the 200)
Note that https://github.com/w3c/resource-timing/issues/345 also mentions two additional
timestamps, which would be added incrementally when tests are authored for them.
* Chrome: yes
* Firefox: [positive](https://github.com/mozilla/standards-positions/issues/722)
* Safari: [positive](https://github.com/WebKit/standards-positions/issues/109)
https://github.com/web-platform-tests/wpt/pull/39881
* Chrome: [1402089](https://bugs.chromium.org/p/chromium/issues/detail?id=1402089)
* Firefox: …
> Add more timing information about (interim) responses

- fetch.bs
As discovered in #1645.
***
<a href="https://whatpr.org/fetch/1652.html" title="Last updated on May 8, 2023, 7:24 AM UTC (91d77b6)">Preview</a> | <a href="https://whatpr.org/fetch/1652/13cb7c9...91d77b6.html" title="Last updated on May 8, 2023, 7:24 AM UTC (91d77b6)">Diff</a>
> Editorial: name variable internalResponse consistently

- fetch.bs
Instead of describing the callbacks one by one, putting emphasis on how/when the caller expects responses (upon completion, chunk-by-chunk, fire-and-forget).
This (hopefully) gives other specs who need to call into Fetch a quick reference between what they're trying to do and the API.
* N/A
* N/A
* N/A
* N/A
***
<a href="https://whatpr.org/fetch/1614.html" title="Last updated on May 11, 2023, 2:30 PM UTC (7e104e6)">Preview</a> | <a href="https://whatpr.org/fetch/1614/aaada1f...7e104e6.html" title="Last updated on May 11, 2023, 2:30 PM UTC (7e104e6)">Diff</a>
> Editorial: Reword how-to section to explain how to use callbacks & controller

- fetch.bs
Fixes #1636.
***
<a href="https://whatpr.org/fetch/1650.html" title="Last updated on May 4, 2023, 8:08 AM UTC (47df1a3)">Preview</a> | <a href="https://whatpr.org/fetch/1650/4502481...47df1a3.html" title="Last updated on May 4, 2023, 8:08 AM UTC (47df1a3)">Diff</a>
> Fully read's processBodyError argument needs to take an exception

- fetch.bs
For https://github.com/whatwg/dom/pull/1152.
---
This is incomplete. https://fetch.spec.whatwg.org/#dom-request-clone needs to be updated as well. While we could probably leave https://fetch.spec.whatwg.org/#request-create (also called by Service Workers) alone, that doesn't seem entirely right as we'd be creating a redundant `AbortSignal` object.
Would the best solution here be that "create" takes a signal(s?) argument and then uses that to create a new composite signal for itself?
It doesn't have to do anything for service workers it seems, but if service workers were to pass an empty list it'd do the same thing it does today.
cc @jakearchibald @shaseley
***
<a href="https://whatpr.org/fetch/1646.html" title="Last updated on May 17, 2023, 12:54 PM UTC (a11ffe2)">Preview</a> | <a …
> Editorial: account for removal of AbortSignal's follow

- fetch.bs
Fixes #1659.
***
<a href="https://whatpr.org/fetch/1660.html" title="Last updated on May 22, 2023, 7:16 AM UTC (230c053)">Preview</a> | <a href="https://whatpr.org/fetch/1660/086e35f...230c053.html" title="Last updated on May 22, 2023, 7:16 AM UTC (230c053)">Diff</a>
> Editorial: define return types of most header list algorithms

- fetch.bs
This ensures that callers of `processResponseEndOfBody` and `processResponseConsumeBody` would receive the correct body and response without additional steps.
Closes #1512
* …
* …
* …
* Chromium: …
* Gecko: …
* WebKit: …
***
<a href="https://whatpr.org/fetch/1645.html" title="Last updated on May 22, 2023, 9:28 AM UTC (788a467)">Preview</a> | <a href="https://whatpr.org/fetch/1645/625897d...788a467.html" title="Last updated on May 22, 2023, 9:28 AM UTC (788a467)">Diff</a>
> Use internalResponse at end of fetch handover

- fetch.bs
Upon reviewing #1645 again it struck me that the first argument to processResponseConsumeBody should not be the internal response. The caller would still have all the same capabilities when it's not and it's safer if it's not.
***
<a href="https://whatpr.org/fetch/1661.html" title="Last updated on May 25, 2023, 4:44 PM UTC (4189234)">Preview</a> | <a href="https://whatpr.org/fetch/1661/9003266...4189234.html" title="Last updated on May 25, 2023, 4:44 PM UTC (4189234)">Diff</a>
> Be more selective with handing out the internal response

- fetch.bs
Exporting this allows other specs to partition network state on the same key used for the HTTP cache.
Network Error Logging, in particular, would like to use this concept by reference (see https://github.com/w3c/network-error-logging/issues/138).
***
<a href="https://whatpr.org/fetch/1670.html" title="Last updated on Jun 7, 2023, 2:53 AM UTC (4c44911)">Preview</a> | <a href="https://whatpr.org/fetch/1670/5eaaf66...4c44911.html" title="Last updated on Jun 7, 2023, 2:53 AM UTC (4c44911)">Diff</a>
> Export "network partition key"

- fetch.bs
There was an `<a for/>` tag, it meant to be `<a for=/>`.
***
<a href="https://whatpr.org/fetch/1689.html" title="Last updated on Jul 21, 2023, 5:57 PM UTC (584008f)">Preview</a> | <a href="https://whatpr.org/fetch/1689/0291bf1...584008f.html" title="Last updated on Jul 21, 2023, 5:57 PM UTC (584008f)">Diff</a>
> Fix broken markup

- fetch.bs
Move the content-range algorithm to a standalone algorithm to avoid the additional inlined steps in Scheme fetch.
Fixes: #1552
***
<a href="https://whatpr.org/fetch/1696.html" title="Last updated on Aug 24, 2023, 12:44 PM UTC (96c4d27)">Preview</a> | <a href="https://whatpr.org/fetch/1696/53e4c3d...96c4d27.html" title="Last updated on Aug 24, 2023, 12:44 PM UTC (96c4d27)">Diff</a>
> Editorial: Create the build a content range algorithm

- fetch.bs
Mainly to give myself more confidence about https://github.com/whatwg/html/issues/9695.
***
<a href="https://whatpr.org/fetch/1699.html" title="Last updated on Sep 6, 2023, 12:21 PM UTC (fc377fd)">Preview</a> | <a href="https://whatpr.org/fetch/1699/f64d43f...fc377fd.html" title="Last updated on Sep 6, 2023, 12:21 PM UTC (fc377fd)">Diff</a>
> Editorial: clarify response's URL list

- fetch.bs
It's either "no-window" or an environment settings object.
***
<a href="https://whatpr.org/fetch/1712.html" title="Last updated on Sep 29, 2023, 7:17 AM UTC (57c1ce1)">Preview</a> | <a href="https://whatpr.org/fetch/1712/c6d7166...57c1ce1.html" title="Last updated on Sep 29, 2023, 7:17 AM UTC (57c1ce1)">Diff</a>
> Correct request's window check

- fetch.bs
The import attributes TC39 proposal has been updated so that HTML can use the expected type (unspecified, `json`, `css`) to affect the fetch request. This PR introduces the `"json"` destination, that will be used to fetch `import "..." with { type: "json" }`.
Ref https://github.com/whatwg/html/pull/9486#discussion_r1273195679, https://github.com/whatwg/html/issues/7233
* Chromium
* WebKit
* https://github.com/web-platform-tests/wpt/pull/41665
* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1491336
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1858078
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=262946
* Deno: https://github.com/denoland/deno/issues/20866
* Node.js: https://github.com/nodejs/node/issues/50116
(See [WHATWG Working Mode: …
> Add `"json"` destination, for JSON modules

- fetch.bs
***
<a href="https://whatpr.org/fetch/1721.html" title="Last updated on Nov 7, 2023, 8:46 AM UTC (e136439)">Preview</a> | <a href="https://whatpr.org/fetch/1721/49bff76...e136439.html" title="Last updated on Nov 7, 2023, 8:46 AM UTC (e136439)">Diff</a>
> Editorial: initialize a response does not have an optional argument

- fetch.bs
Clarify that, although CORS-preflight requests systematically include an Access-Control-Request-Method header, they do not systematically include an Access-Control-Request-Headers header.
Fixes #1717.
***
<a href="https://whatpr.org/fetch/1719.html" title="Last updated on Oct 24, 2023, 12:14 PM UTC (6962c78)">Preview</a> | <a href="https://whatpr.org/fetch/1719/aa6f53e...6962c78.html" title="Last updated on Oct 24, 2023, 12:14 PM UTC (6962c78)">Diff</a>
> Editorial: clarify preflight-request headers

- review-drafts/2023-12.bs
The [December 2023 Review Draft](https://fetch.spec.whatwg.org/review-drafts/2023-12/) for this Workstream will be published shortly after merging this pull request.
Under the [WHATWG IPR Policy](https://whatwg.org/ipr-policy), Participants may, within 45 days after publication of a Review Draft, exclude certain Essential Patent Claims from the Review Draft Licensing Obligations. See the [IPR Policy](https://whatwg.org/ipr-policy) for details.
***
<a href="https://whatpr.org/fetch/1728.html" title="Last updated on Dec 18, 2023, 12:02 PM UTC (cc7437c)">Preview</a> | <a href="https://whatpr.org/fetch/1728/d6bf406...cc7437c.html" title="Last updated on Dec 18, 2023, 12:02 PM UTC (cc7437c)">Diff</a>
> Review Draft Publication: December 2023

- fetch.bs
This is referenced [1] by the Service Worker spec, so should either be exported or something else to achieve the same thing would need to exist (forwarding the "abort reason" from a fetch controller to an AbortController; note that the service worker algorithm is currently extra confusing because it uses the same variable name for both "controller" objects).
[1]: https://w3c.github.io/ServiceWorker/#clients-openwindow:~:text=If%20controller%E2%80%99s%20serialized%20abort%20reason%20is%20non%2Dnull
***
<a href="https://whatpr.org/fetch/1736.html" title="Last updated on Feb 12, 2024, 6:54 PM UTC (d5affe7)">Preview</a> | <a href="https://whatpr.org/fetch/1736/8dd73db...d5affe7.html" title="Last updated on Feb 12, 2024, 6:54 PM UTC (d5affe7)">Diff</a>
> Editorial: Export fetch controller/serialized abort reason

- fetch.bs
This should be more future proof.
Fixes #1744.
***
<a href="https://whatpr.org/fetch/1745.html" title="Last updated on Apr 29, 2024, 2:16 PM UTC (840df72)">Preview</a> | <a href="https://whatpr.org/fetch/1745/4c3750d...840df72.html" title="Last updated on Apr 29, 2024, 2:16 PM UTC (840df72)">Diff</a>
> Rename http3Only to requireUnreliable

- fetch.bs
The other uses of this phrase in this document are links, just not the one right at the start of the definition of `fetch`.
***
<a href="https://whatpr.org/fetch/1752.html" title="Last updated on May 4, 2024, 5:15 AM UTC (1836662)">Preview</a> | <a href="https://whatpr.org/fetch/1752/14bad1d...1836662.html" title="Last updated on May 4, 2024, 5:15 AM UTC (1836662)">Diff</a>
> Editorial: link "a new promise"

- fetch.bs
Fixes https://github.com/whatwg/fetch/issues/1675, maybe.
@annevk in that issue also points out that the [extract a body [...]](https://fetch.spec.whatwg.org/#concept-bodyinit-extract) algorithm also creates a Uint8Array in an ad-hoc way, which I've also tried to fix. Unfortunately I don't know what realm to use there - unlike the original issue, these aren't method steps. I am guessing that when the realm is unspecified (which it very often isn't - for example, earlier in the same algorithm there is "set stream to a new ReadableStream object" without a realm argument), it's implicitly the current realm? But maybe we need to thread a realm argument into this algorithm (and quite a few others), or possibly just explicitly pass "the current realm".
(If this right I'll follow up with a PR …
> Editorial: Fix realmless ArrayBuffer creation

- fetch.bs
Adds a `bytes()` method to get a `Uint8Array` to `Body`, instead of requiring users to get an `ArrayBuffer` and then wrap it.
Fixes https://github.com/whatwg/fetch/issues/1732.
* Chromium: https://github.com/whatwg/fetch/issues/1732#issuecomment-2066280001
* Gecko: https://github.com/whatwg/fetch/issues/1732#issuecomment-2036463542
* WebKit: https://github.com/whatwg/fetch/issues/1732#issuecomment-2036440127
* https://github.com/web-platform-tests/wpt/pull/46198
* Chromium: https://issues.chromium.org/issues/340206277
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1896475
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=274102
* Deno (not for CORS changes): https://github.com/denoland/deno/issues/23790
* Node (undici): https://github.com/nodejs/undici/issues/3256
* Bun: …
> Add bytes() method to Body mixin

- fetch.bs
***
<a href="https://whatpr.org/fetch/1758.html" title="Last updated on Jun 5, 2024, 6:35 PM UTC (cc13052)">Preview</a> | <a href="https://whatpr.org/fetch/1758/1085f4f...cc13052.html" title="Last updated on Jun 5, 2024, 6:35 PM UTC (cc13052)">Diff</a>
> Fix outdated HTML PR link

- review-drafts/2024-06.bs
The [June 2024 Review Draft](https://fetch.spec.whatwg.org/review-drafts/2024-06/) for this Workstream will be published shortly after merging this pull request.
Under the [WHATWG IPR Policy](https://whatwg.org/ipr-policy), Participants may, within 45 days after publication of a Review Draft, exclude certain Essential Patent Claims from the Review Draft Licensing Obligations. See the [IPR Policy](https://whatwg.org/ipr-policy) for details.
***
<a href="https://whatpr.org/fetch/1760.html" title="Last updated on Jun 17, 2024, 11:18 AM UTC (7dba5fc)">Preview</a> | <a href="https://whatpr.org/fetch/1760/7db7aca...7dba5fc.html" title="Last updated on Jun 17, 2024, 11:18 AM UTC (7dba5fc)">Diff</a>
> Review Draft Publication: June 2024

- fetch.bs
Correct how it handles when a header is present but has no value (should be a list solely containing an empty string value) and when there is a trailing comma (should be a list ending with an empty string value).
Fixes #1768.
---
@domenic @MattMenke2 this was an oversight in #831 it appears. If you'd like to review in addition to @CarloCannas I'd appreciate it. Thanks!
***
<a href="https://whatpr.org/fetch/1769.html" title="Last updated on Aug 19, 2024, 1:43 PM UTC (0334504)">Preview</a> | <a href="https://whatpr.org/fetch/1769/4cb3cf2...0334504.html" title="Last updated on Aug 19, 2024, 1:43 PM UTC (0334504)">Diff</a>
> Make get, decode, and split handle edge cases correctly

- fetch.bs
Previously, the code implicitly guaranteed that a requests origin could not be "client" after Step 10 of
https://fetch.spec.whatwg.org/#concept-fetch.
Other algorithms then simply relied on this fact. This is confusing. Instead, we now explicitly assert that the origin is not client whereever we need it.
This closes #1773
---
***
<a href="https://whatpr.org/fetch/1776.html" title="Last updated on Oct 1, 2024, 7:43 AM UTC (6835582)">Preview</a> | <a href="https://whatpr.org/fetch/1776/edfa8d1...6835582.html" title="Last updated on Oct 1, 2024, 7:43 AM UTC (6835582)">Diff</a>
> Clarify that request.origin cannot be "client" at certain points

- fetch.bs
Fetch appears aligned with the changes described in https://httpwg.org/specs/rfc9651.html#changes. Sec-Purpose is the sole structured header Fetch defines and it does not use ABNF for its definition.
***
<a href="https://whatpr.org/fetch/1782.html" title="Last updated on Oct 24, 2024, 9:19 PM UTC (8fb3736)">Preview</a> | <a href="https://whatpr.org/fetch/1782/761c414...8fb3736.html" title="Last updated on Oct 24, 2024, 9:19 PM UTC (8fb3736)">Diff</a>
> Meta: reference new Structured Field Values RFC

- fetch.bs
Fixes #1780 
* Firefox (already shipped)
* [Chrome](https://groups.google.com/a/chromium.org/g/blink-dev/c/WJnjKYY2iSs/m/Rh9HlI3lAwAJ?utm_medium=email&utm_source=footer)
* HSTS is not presently tested via WPT
* Chromium: https://issues.chromium.org/issues/41251622
* Gecko: n/a
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=282054
* Deno (not for CORS changes): https://github.com/denoland/deno/issues/26736
***
<a href="https://whatpr.org/fetch/1781.html" title="Last updated on Nov 5, 2024, 8:54 AM UTC (acd9cac)">Preview</a> | <a href="https://whatpr.org/fetch/1781/761c414...acd9cac.html" title="Last updated on Nov 5, 2024, 8:54 AM UTC (acd9cac)">Diff</a>
> Skip localhost when evaluating HSTS upgrades

- fetch.bs
Partition Blob URL fetches by Storage Key
This change updates the spec to partition Blob URL fetches by Storage Key. This change is part of broader changes discussed in https://github.com/w3c/FileAPI/issues/153#issuecomment-2330085478. Specifically, we will also:
- Partition Blob URL revocation by storage key - https://github.com/w3c/FileAPI/pull/201
- Enforce noopener for cross-top-level-site Blob URLs - (Spec changes for this will follow)
I considered incorporating the Storage Key checks into the "resolve a blob URL" algorithm instead, but it seemed that this would require an environment settings object to be available as part of https://url.spec.whatwg.org/#url-parsing, and I'm not sure whether that is the case / a change we want.
* Firefox has already implemented this - …
> Partition Blob URL fetches by Storage Key

- fetch.bs
This has been wrong for a decade (see 38647562f94d396b77c62f77b4024ee21a1bb400) and nobody noticed until now.
Fixes #1794.
---
Omitting template as this has been implemented "correctly" for a decade as well.
***
<a href="https://whatpr.org/fetch/1795.html" title="Last updated on Dec 12, 2024, 8:08 AM UTC (75893d9)">Preview</a> | <a href="https://whatpr.org/fetch/1795/0ce45ae...75893d9.html" title="Last updated on Dec 12, 2024, 8:08 AM UTC (75893d9)">Diff</a>
> Correct Response's statusText check

- fetch.bs
This doesn't have observable effects at the moment, but is a preparation for deferred fetching where populating the request
from client (specifically policy container) needs to happen before fetching.
(https://github.com/whatwg/meta/blob/main/COMMITTING.md) to use. 
***
<a href="https://whatpr.org/fetch/1793.html" title="Last updated on Dec 16, 2024, 11:32 AM UTC (708d8c1)">Preview</a> | <a href="https://whatpr.org/fetch/1793/0ce45ae...708d8c1.html" title="Last updated on Dec 16, 2024, 11:32 AM UTC (708d8c1)">Diff</a>
> Editorial: Move handling of request 'client' to its own steps

- fetch.bs
Fixes #1798.
***
<a href="https://whatpr.org/fetch/1799.html" title="Last updated on Dec 18, 2024, 7:21 AM UTC (a5fa148)">Preview</a> | <a href="https://whatpr.org/fetch/1799/c8a0408...a5fa148.html" title="Last updated on Dec 18, 2024, 7:21 AM UTC (a5fa148)">Diff</a>
> Editorial: parsing application/x-www-form-urlencoded never fails

- fetch.bs
***
<a href="https://whatpr.org/fetch/1804.html" title="Last updated on Jan 21, 2025, 8:13 AM UTC (955bf1a)">Preview</a> | <a href="https://whatpr.org/fetch/1804/5dfed9d...955bf1a.html" title="Last updated on Jan 21, 2025, 8:13 AM UTC (955bf1a)">Diff</a>
> [Editorial] Fix build issues from recent updates to bikeshed

- fetch.bs
*pullAlgorithm* refers to *stream*, so we should define *stream* first.
***
<a href="https://whatpr.org/fetch/1817.html" title="Last updated on Mar 27, 2025, 12:11 PM UTC (dbdabea)">Preview</a> | <a href="https://whatpr.org/fetch/1817/07662d3...dbdabea.html" title="Last updated on Mar 27, 2025, 12:11 PM UTC (dbdabea)">Diff</a>
> Editorial: define stream variable before using it

- fetch.bs
After much discussion in #1820 and #1821, this seems to be more correct. User prompts are not tied to specific `Window`s, and certainly not to the client's `Window`. They are tied to a traversable navigable, i.e. "browser tab", and that browser tab should ideally be blanked out and updated to reflect that it's the destination that's causing the prompt, not the request client.
Closes #1820. Closes #1821. Helps https://github.com/whatwg/html/pull/11250 specify browser-initiated navigations better.
* This seems to match all browser behavior.
* Not really testable in WPT, due to https://github.com/web-platform-tests/wpt/issues/16019 I believe.
* Chromium: N/A
* Gecko: N/A, although maybe a bug to encourage the blanking-out behavior would be appreciated?
* WebKit: N/A, although maybe a bug to …
> Replace request's "window" with "traversable for user prompts"

- fetch.bs
Tiny markup error detected by an unreleased Bikeshed version.
***
<a href="https://whatpr.org/fetch/1829.html" title="Last updated on May 23, 2025, 5:44 PM UTC (1bf9400)">Preview</a> | <a href="https://whatpr.org/fetch/1829/41185ac...1bf9400.html" title="Last updated on May 23, 2025, 5:44 PM UTC (1bf9400)">Diff</a>
> Fix markup

- fetch.bs
Rather than linking to a draft of DNS SVCB, it seems ideal to link to the published RFC now that it's available. This is an editorial change, as I don't believe there were any meaningful changes between -12 and the published RFC.
***
<a href="https://whatpr.org/fetch/1830.html" title="Last updated on May 26, 2025, 6:11 AM UTC (70d1951)">Preview</a> | <a href="https://whatpr.org/fetch/1830/97f308e...70d1951.html" title="Last updated on May 26, 2025, 6:11 AM UTC (70d1951)">Diff</a>
> [Editorial] Shift SVCB to reference RFC9460.

- fetch.bs
This is a followup on https://github.com/w3c/webappsec-subresource-integrity/pull/133:
* Integrating the algorithms there into Main Fetch
* Defining request destination as a type, so it can be used there.
* Chromium has [shipped](https://groups.google.com/a/chromium.org/g/blink-dev/c/Q304_OkDAZA/m/GDdr27kSDwAJ)
* WebKit is likely [supportive](https://github.com/WebKit/standards-positions/issues/458#issuecomment-2879100268)
* Mozilla is [supportive](https://github.com/mozilla/standards-positions/issues/1173#issuecomment-2824076789)
https://wpt.fyi/results/subresource-integrity/integrity-policy?label=experimental&label=master&aligned
* Chromium: https://issues.chromium.org/issues/412588111
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1960904
* WebKit: …
> Integrity-Policy integration

- fetch.bs
The full timing info is there for navigation timing, which is already available at document creation (which happens right after the handover).
This is a spec bug, while implementations/WPT test the right behavior.
Already implemented
* https://wpt.fyi/results/navigation-timing/nav2-test-instance-accessible-from-the-start.html?label=experimental&label=master&aligned
- [x [Implementation bugs](https://github.com/whatwg/meta/blob/main/MAINTAINERS.md#handling-pull-requests) are filed:
* N/A
- [x [MDN issue](https://github.com/whatwg/meta/blob/main/MAINTAINERS.md#handling-pull-requests) is filed: N/A
***
<a href="https://whatpr.org/fetch/1842.html" title="Last updated on Jul 15, 2025, 7:20 PM UTC (dae71a0)">Preview</a> | <a href="https://whatpr.org/fetch/1842/5261b51...dae71a0.html" …
> Move full timing info setting outside of processResponseEndOfBody steps.

- fetch.bs
Tests: https://github.com/web-platform-tests/wpt/pull/54227.
* WebKit
* Gecko (confirmed out-of-band)
* https://github.com/web-platform-tests/wpt/pull/54227
* Chromium: N/A
* Gecko: N/A
* WebKit: N/A
***
<a href="https://whatpr.org/fetch/1847.html" title="Last updated on Aug 11, 2025, 1:16 PM UTC (269de56)">Preview</a> | <a href="https://whatpr.org/fetch/1847/90e1a1e...269de56.html" title="Last updated on Aug 11, 2025, 1:16 PM UTC (269de56)">Diff</a>
> Block port 0

- fetch.bs
This matches what all major web browsers already do and navigator.appVersion relies on this to a fault. See https://github.com/whatwg/html/issues/11630 for context.
***
<a href="https://whatpr.org/fetch/1855.html" title="Last updated on Sep 9, 2025, 4:31 PM UTC (c560ab5)">Preview</a> | <a href="https://whatpr.org/fetch/1855/79b4314...c560ab5.html" title="Last updated on Sep 9, 2025, 4:31 PM UTC (c560ab5)">Diff</a>
> Encourage web browser User-Agent value to start with `Mozilla/5.0 (`

- fetch.bs
The getter steps [1] specify to return `this.signal`. Its signal is nullable [2], but it is always initialized in the constructor and when cloning.
[1]: https://fetch.spec.whatwg.org/#dom-request-signal
[2]: https://fetch.spec.whatwg.org/#request-signal
***
<a href="https://whatpr.org/fetch/1856.html" title="Last updated on Sep 18, 2025, 1:54 PM UTC (f275bd3)">Preview</a> | <a href="https://whatpr.org/fetch/1856/e28f9a5...f275bd3.html" title="Last updated on Sep 18, 2025, 1:54 PM UTC (f275bd3)">Diff</a>
> Add note that `signal` is always initialized

- fetch.bs
`input` is either a string or a request. Since this links to body, it was probably meant to be `inputBody` instead.
***
<a href="https://whatpr.org/fetch/1857.html" title="Last updated on Sep 25, 2025, 7:16 PM UTC (382cdaa)">Preview</a> | <a href="https://whatpr.org/fetch/1857/ed04423...382cdaa.html" title="Last updated on Sep 25, 2025, 7:16 PM UTC (382cdaa)">Diff</a>
> Editorial: fix typo for inputBody
