whatwg/fetch

Overview.html
Overview.src.html

See https://github.com/whatwg/html/pull/840#discussion_r55568720 for discussion and context. Many
thanks to Simon Pieters for helping out.

Define the WebSocket subprotocol check as part of response validation

---

Overview.html
Overview.src.html

Clarify why request's url field exists

---

Overview.html
Overview.src.html

Editorial: clarify cache match conditions

---

Overview.html
Overview.src.html

Editorial: make an HTTPS state value its own thing

---

Overview.html
Overview.src.html

Explain CORS protocol and credentials interaction

---

Overview.html
Overview.src.html

Add CORS protocol examples

---

Overview.html
Overview.src.html

Remove an unused variable

---

Overview.html
Overview.src.html

A request needs to be created with a URL

---

Overview.html
Overview.src.html

See tabatkins/bikeshed#773 for context.

Editorial: Add Bikeshed metadata for 'request'

---

Overview.html
Overview.src.html

In preparation for bikeshed conversion, see #398 & #399

Add ids to headings and examples

---

fetch.bs
fetch.html

URL renamed the non-relative flag.

Update for URL's cannot-be-a-base-URL flag

---

fetch.bs

For linking to from the service worker spec

Export various things for service worker

---

.travis.yml
fetch.bs

Also fix the HTML and HTTP header definitions and HTTP header links in
the process.

Meta: run HTML checker on generated HTML

---

fetch.bs

Handle null and failure for Access-Control-Expose-Headers

---

fetch.bs

Clarify Body package data algorithm with multipart/form-data MIME type

---

fetch.bs

Clarify the ABNF flavor in use

---

.pr-preview.json
README.md
fetch.bs

See https://github.com/whatwg/meta/issues/16.

Meta: enable PR review

---

fetch.bs

Fixes #172.
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/annevk/cors-server/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/b59c72b...346e45d.html)

Clarify requirements on a CORS server

---

fetch.bs

***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/annevk/csp-column/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/d7052e2...d462491.html)

Editorial: correct CSP column

---

fetch.bs

***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/annevk/rethrow/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/9fa071b...efd3ffa.html)

Editorial: remove "rethrow" per Infra

---

fetch.bs

See https://github.com/whatwg/infra/pull/156.
***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/annevk/json/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/0bcd5df...37d8d94.html)

Use Infra for JSON parsing

---

fetch.bs

@domenic Addressing your Request domintro nits here, and will add the other `init` member info to the constructor entry in the domintro box in another PR soon. That should finish the Request stuff.
(see https://github.com/whatwg/fetch/pull/617#issuecomment-336970308)
***
[Preview](https://s3.amazonaws.com/pr-preview/domfarolino/fetch/request-domintro-nits.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/978cf9a...domfarolino:ff8fe74.html)

Address Domenic's Request domintro nits

---

fetch.bs

Yehuda contributed a lot to the early discussions around the fetch() API.
(Also cleanup a couple of references.)
Closes #611.
***
<a href="https://fetch.spec.whatwg.org/branch-snapshots/annevk/ack-yehuda/" title="Last updated on Nov 24, 2017, 9:34 AM GMT">Preview</a> | <a href="https://s3.amazonaws.com/pr-preview/whatwg/fetch/860ab86...8941608.html" title="Last updated on Nov 24, 2017, 9:34 AM GMT">Diff</a>

Acknowledge Yehuda Katz

---

fetch.bs

Matches https://w3c.github.io/webcrypto/Overview.html.
***
<a href="https://whatpr.org/fetch/649.html" title="Last updated on Dec 20, 2017, 9:44 AM GMT (aa87e33)">Preview</a> | <a href="https://whatpr.org/fetch/649/4c0227b...aa87e33.html" title="Last updated on Dec 20, 2017, 9:44 AM GMT (aa87e33)">Diff</a>

Editorial: spell cypher as cipher

---

fetch.bs

Fixes #639.
***
<a href="https://pr-preview.s3.amazonaws.com/whatwg/fetch/pull/640.html" title="Last updated on Nov 30, 2017, 9:06 AM GMT">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/whatwg/fetch/fd28675...d6f757b.html" title="Last updated on Nov 30, 2017, 9:06 AM GMT">Diff</a>

Editorial: address Bikeshed and minor wording issues

---

LICENSE
fetch.bs

<del>Also fixes a few linking errors and RFC 2119 misuses.</del><ins>Done in #640 instead.</ins>
---
Do not merge until https://github.com/tabatkins/bikeshed/pull/1155 is merged.
***
<a href="https://whatpr.org/fetch/651.html" title="Last updated on Jan 4, 2018, 5:19 PM GMT (9a4c326)">Preview</a> | <a href="https://whatpr.org/fetch/651/4fe4385...9a4c326.html" title="Last updated on Jan 4, 2018, 5:19 PM GMT (9a4c326)">Diff</a>

Meta: use new WHATWG boilerplate and license

---

fetch.bs

Also clean up some editorial issues with that section in general.
Fixes #625.
/cc @ricea

Make observability examples nitpick-proof

---

CONTRIBUTING.md
README.md

Helps with https://github.com/whatwg/meta/issues/65.

Meta: reference whatwg/meta resources

---

fetch.bs

Tests will be done as part of https://bugzilla.mozilla.org/show_bug.cgi?id=1427978.
Fixes #629.
***
<a href="https://whatpr.org/fetch/655.html" title="Last updated on Jan 6, 2018, 11:57 AM GMT (c7e686a)">Preview</a> | <a href="https://whatpr.org/fetch/655/a1d387c...c7e686a.html" title="Last updated on Jan 6, 2018, 11:57 AM GMT (c7e686a)">Diff</a>

Do not allow CORS responses to "same-origin" requests

---

fetch.bs

WPT PR is at https://github.com/w3c/web-platform-tests/pull/9039
***
<a href="https://whatpr.org/fetch/663.html" title="Last updated on Jan 23, 2018, 12:15 PM GMT (b058355)">Preview</a> | <a href="https://whatpr.org/fetch/663/9862bc5...b058355.html" title="Last updated on Jan 23, 2018, 12:15 PM GMT (b058355)">Diff</a>

Return a network error in case of no-cors mode and redirect being not follow

---

fetch.bs

Also consistly make appending these headers a "should".
Fixes #475.
***
<a href="https://whatpr.org/fetch/704.html" title="Last updated on Apr 17, 2018, 3:34 PM GMT (7e99f75)">Preview</a> | <a href="https://whatpr.org/fetch/704/860922f...7e99f75.html" title="Last updated on Apr 17, 2018, 3:34 PM GMT (7e99f75)">Diff</a>

Adjust casing of client hints

---

fetch.bs

Tests: ...
Fixes #657.
***
<a href="https://whatpr.org/fetch/710.html" title="Last updated on Apr 23, 2018, 12:40 PM GMT (1c76118)">Preview</a> | <a href="https://whatpr.org/fetch/710/fd8ee5c...1c76118.html" title="Last updated on Apr 23, 2018, 12:40 PM GMT (1c76118)">Diff</a>

Handle failure while handling content codings

---

fetch.bs

***
<a href="https://whatpr.org/fetch/709.html" title="Last updated on Apr 23, 2018, 5:00 PM GMT (54d4d88)">Preview</a> | <a href="https://whatpr.org/fetch/709/fd8ee5c...54d4d88.html" title="Last updated on Apr 23, 2018, 5:00 PM GMT (54d4d88)">Diff</a>

Editorial: remove most substep usage

---

fetch.bs

See https://github.com/whatwg/infra/pull/172.
***
<a href="https://whatpr.org/fetch/702.html" title="Last updated on Apr 26, 2018, 12:51 PM GMT (fe99602)">Preview</a> | <a href="https://whatpr.org/fetch/702/0dec453...fe99602.html" title="Last updated on Apr 26, 2018, 12:51 PM GMT (fe99602)">Diff</a>

Use Infra's abort when

---

fetch.bs

***
<a href="https://whatpr.org/fetch/783.html" title="Last updated on Aug 10, 2018, 7:14 AM GMT (8cb9676)">Preview</a> | <a href="https://whatpr.org/fetch/783/b3492ec...8cb9676.html" title="Last updated on Aug 10, 2018, 7:14 AM GMT (8cb9676)">Diff</a>

Add [for] attributes to remove bikeshed errors.

---

fetch.bs

Fixes #697.
***
<a href="https://whatpr.org/fetch/795.html" title="Last updated on Aug 21, 2018, 7:14 AM GMT (6c0106b)">Preview</a> | <a href="https://whatpr.org/fetch/795/c385007...6c0106b.html" title="Last updated on Aug 21, 2018, 7:14 AM GMT (6c0106b)">Diff</a>

Editorial: url ➡️ URL

---

fetch.bs

And in general be more explicit about the objects involved.
***
<a href="https://whatpr.org/fetch/803.html" title="Last updated on Aug 22, 2018, 9:45 AM GMT (5336b87)">Preview</a> | <a href="https://whatpr.org/fetch/803/5088fce...5336b87.html" title="Last updated on Aug 22, 2018, 9:45 AM GMT (5336b87)">Diff</a>

Editorial: be more consistent about the context object

---

fetch.bs

These commits address the shortcomings discussed in #748. I've yet to add tests (probably not today).
***
<a href="https://whatpr.org/fetch/833.html" title="Last updated on Nov 14, 2018, 3:49 PM GMT (fbab8af)">Preview</a> | <a href="https://whatpr.org/fetch/833/a243f1f...fbab8af.html" title="Last updated on Nov 14, 2018, 3:49 PM GMT (fbab8af)">Diff</a>

Headers API corrections

---

fetch.bs

Replace uses with "getting a name from a header list".
***
<a href="https://whatpr.org/fetch/842.html" title="Last updated on Nov 29, 2018, 4:57 PM GMT (d5381f4)">Preview</a> | <a href="https://whatpr.org/fetch/842/80d26b6...d5381f4.html" title="Last updated on Nov 29, 2018, 4:57 PM GMT (d5381f4)">Diff</a>

Remove "combined value" concept

---

fetch.bs

Fixes #845.
***
<a href="https://whatpr.org/fetch/850.html" title="Last updated on Dec 12, 2018, 11:26 AM GMT (9991eaf)">Preview</a> | <a href="https://whatpr.org/fetch/850/4973765...9991eaf.html" title="Last updated on Dec 12, 2018, 11:26 AM GMT (9991eaf)">Diff</a>

Editorial: use %s ABNF notation

---

fetch.bs

Fixes #837.
***
<a href="https://whatpr.org/fetch/849.html" title="Last updated on Dec 12, 2018, 11:48 AM GMT (1978147)">Preview</a> | <a href="https://whatpr.org/fetch/849/e69e9c2...1978147.html" title="Last updated on Dec 12, 2018, 11:48 AM GMT (1978147)">Diff</a>

Editorial: add syntax highlighting

---

fetch.bs

***
<a href="https://whatpr.org/fetch/857.html" title="Last updated on Jan 15, 2019, 9:34 AM UTC (da40743)">Preview</a> | <a href="https://whatpr.org/fetch/857/c6b3a75...da40743.html" title="Last updated on Jan 15, 2019, 9:34 AM UTC (da40743)">Diff</a>

Follow changes from whatwg/url#371.

---

fetch.bs

See https://github.com/heycam/webidl/pull/750.
***
<a href="https://whatpr.org/fetch/919.html" title="Last updated on Aug 9, 2019, 8:32 AM UTC (9c476d1)">Preview</a> | <a href="https://whatpr.org/fetch/919/b7de58c...9c476d1.html" title="Last updated on Aug 9, 2019, 8:32 AM UTC (9c476d1)">Diff</a>

Align with IDL dictionary changes

---

fetch.bs

Tests: web-platform-tests/wpt#18739.
Closes: #922.
***
<a href="https://whatpr.org/fetch/941.html" title="Last updated on Sep 26, 2019, 5:51 PM UTC (daac153)">Preview</a> | <a href="https://whatpr.org/fetch/941/eff7659...daac153.html" title="Last updated on Sep 26, 2019, 5:51 PM UTC (daac153)">Diff</a>

Add Accept: */* to CORS-preflight requests' headers

---

fetch.bs

Closes #953.
***
<a href="https://whatpr.org/fetch/963.html" title="Last updated on Nov 11, 2019, 10:31 AM UTC (d8ac077)">Preview</a> | <a href="https://whatpr.org/fetch/963/65138f3...d8ac077.html" title="Last updated on Nov 11, 2019, 10:31 AM UTC (d8ac077)">Diff</a>

Editorial: mention the tainted origin flag less

---

.editorconfig
.pr-preview.json
Makefile
fetch.bs

See https://github.com/whatwg/spec-factory for details.
***
<a href="https://whatpr.org/fetch/1023.html" title="Last updated on Apr 23, 2020, 3:16 PM UTC (126228f)">Preview</a> | <a href="https://whatpr.org/fetch/1023/1eb53ea...126228f.html" title="Last updated on Apr 23, 2020, 3:16 PM UTC (126228f)">Diff</a>

Meta: update repository files

---

fetch.bs

***
<a href="https://whatpr.org/fetch/1086.html" title="Last updated on Aug 28, 2020, 8:41 AM UTC (2ecdd98)">Preview</a> | <a href="https://whatpr.org/fetch/1086/cd38eca...2ecdd98.html" title="Last updated on Aug 28, 2020, 8:41 AM UTC (2ecdd98)">Diff</a>

Editorial: Fix sentence fragment about header list

---

fetch.bs

***
<a href="https://whatpr.org/fetch/1095.html" title="Last updated on Sep 29, 2020, 2:45 PM UTC (e162a7c)">Preview</a> | <a href="https://whatpr.org/fetch/1095/bd85294...e162a7c.html" title="Last updated on Sep 29, 2020, 2:45 PM UTC (e162a7c)">Diff</a>

Meta: link Review Draft

---

fetch.bs

Closes #956.
cc @martinthomson
***
<a href="https://whatpr.org/fetch/1106.html" title="Last updated on Nov 3, 2020, 8:11 AM UTC (6502e1e)">Preview</a> | <a href="https://whatpr.org/fetch/1106/515e6bb...6502e1e.html" title="Last updated on Nov 3, 2020, 8:11 AM UTC (6502e1e)">Diff</a>

Document how new protocols relate to port blocking

---

fetch.bs

Closes #1110.
(I might try to get the other CSP algorithms exported so I can link to them in this manner.)
***
<a href="https://whatpr.org/fetch/1111.html" title="Last updated on Nov 6, 2020, 5:24 PM UTC (909f7bf)">Preview</a> | <a href="https://whatpr.org/fetch/1111/65ec6e9...909f7bf.html" title="Last updated on Nov 6, 2020, 5:24 PM UTC (909f7bf)">Diff</a>

Meta: integrate better with CSP

---

fetch.bs

And address a cross-reference problem and unreachable return.
***
<a href="https://whatpr.org/fetch/1138.html" title="Last updated on Jan 12, 2021, 3:45 PM UTC (7324e67)">Preview</a> | <a href="https://whatpr.org/fetch/1138/07ef806...7324e67.html" title="Last updated on Jan 12, 2021, 3:45 PM UTC (7324e67)">Diff</a>

Editorial: consistify clone() method of Request and Response

---

fetch.bs

***
<a href="https://whatpr.org/fetch/1154.html" title="Last updated on Jan 30, 2021, 2:52 PM UTC (28969fa)">Preview</a> | <a href="https://whatpr.org/fetch/1154/d070ea2...28969fa.html" title="Last updated on Jan 30, 2021, 2:52 PM UTC (28969fa)">Diff</a>

Editorial: uppercase remaning instances of url

---

fetch.bs

Fixes #695.
***
<a href="https://whatpr.org/fetch/1158.html" title="Last updated on Feb 1, 2021, 3:01 PM UTC (52465c7)">Preview</a> | <a href="https://whatpr.org/fetch/1158/98f23db...52465c7.html" title="Last updated on Feb 1, 2021, 3:01 PM UTC (52465c7)">Diff</a>

Meta: internal response belongs to filtered response

---

fetch.bs

***
<a href="https://whatpr.org/fetch/1151.html" title="Last updated on Jan 30, 2021, 8:48 AM UTC (a36d81b)">Preview</a> | <a href="https://whatpr.org/fetch/1151/d070ea2...a36d81b.html" title="Last updated on Jan 30, 2021, 8:48 AM UTC (a36d81b)">Diff</a>

Editorial: en-US is sanitize

---

fetch.bs

***
<a href="https://whatpr.org/fetch/1115.html" title="Last updated on Jan 15, 2021, 7:39 AM UTC (296fb0f)">Preview</a> | <a href="https://whatpr.org/fetch/1115/c5f8177...296fb0f.html" title="Last updated on Jan 15, 2021, 7:39 AM UTC (296fb0f)">Diff</a>

Editorial: Fix CORS legal and illegal combinations table

---

fetch.bs

(CI will fail until https://github.com/whatwg/url/pull/576 lands.)
***
<a href="https://whatpr.org/fetch/1160.html" title="Last updated on Feb 2, 2021, 7:13 PM UTC (e360436)">Preview</a> | <a href="https://whatpr.org/fetch/1160/49085f9...e360436.html" title="Last updated on Feb 2, 2021, 7:13 PM UTC (e360436)">Diff</a>

Editorial: URL dropped flag language

---

fetch.bs

This simplifies some algorithms and helps with #954.
***
<a href="https://whatpr.org/fetch/1152.html" title="Last updated on Feb 2, 2021, 2:20 PM UTC (a75ffa6)">Preview</a> | <a href="https://whatpr.org/fetch/1152/987c3fd...a75ffa6.html" title="Last updated on Feb 2, 2021, 2:20 PM UTC (a75ffa6)">Diff</a>

Editorial: rename keepalive flag to keepalive

---

fetch.bs

Closes #1168.
***
<a href="https://whatpr.org/fetch/1169.html" title="Last updated on Feb 15, 2021, 7:58 AM UTC (7e00f43)">Preview</a> | <a href="https://whatpr.org/fetch/1169/12dd6fa...7e00f43.html" title="Last updated on Feb 15, 2021, 7:58 AM UTC (7e00f43)">Diff</a>

Editorial: correct markup

---

fetch.bs

***
<a href="https://whatpr.org/fetch/1192.html" title="Last updated on Mar 12, 2021, 1:26 PM UTC (dcb2006)">Preview</a> | <a href="https://whatpr.org/fetch/1192/4202f5c...dcb2006.html" title="Last updated on Mar 12, 2021, 1:26 PM UTC (dcb2006)">Diff</a>

Editorial: update Mixed Content and SFV references

---

fetch.bs

Follows https://github.com/whatwg/streams/pull/1110. Closes #1205.
***
<a href="https://whatpr.org/fetch/1207.html" title="Last updated on Mar 31, 2021, 3:38 PM UTC (2ebdb94)">Preview</a> | <a href="https://whatpr.org/fetch/1207/73f01f7...2ebdb94.html" title="Last updated on Mar 31, 2021, 3:38 PM UTC (2ebdb94)">Diff</a>

Meta: "set up" ReadableStreams instead of "create"

---

fetch.bs

***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Apr 12, 2021, 6:33 AM UTC)_.
<details>
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related URL](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwhatpr.org%2Ffetch%2F1206%2Ff361d9c.html&doc2=https%3A%2F%2Fwhatpr.org%2Ffetch%2F1206.html)
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal …
```

Editorial: tweak wording for "The Web Origin Concept" obsolescence

---

fetch.bs

Tests: https://github.com/web-platform-tests/wpt/pull/28445.
Fixes #1191.
* Chrome
* Firefox
* Safari
* See above.
* Chrome: shipped
* Firefox: shipped
* Safari: in progress
***
<a href="https://whatpr.org/fetch/1214.html" title="Last updated on Apr 13, 2021, 10:24 AM UTC (fcea112)">Preview</a> | <a href="https://whatpr.org/fetch/1214/c3d8306...fcea112.html" title="Last updated on Apr 13, 2021, 10:24 AM UTC (fcea112)">Diff</a>

Block port 10080

---

fetch.bs

***
<a href="https://whatpr.org/fetch/1240.html" title="Last updated on May 25, 2021, 12:27 PM UTC (2cc1b55)">Preview</a> | <a href="https://whatpr.org/fetch/1240/b6c6283...2cc1b55.html" title="Last updated on May 25, 2021, 12:27 PM UTC (2cc1b55)">Diff</a>

Editorial: modernize connection prose

---

fetch.bs

@noamr @yoavweiss could you review?
***
<a href="https://whatpr.org/fetch/1248.html" title="Last updated on Jun 3, 2021, 1:57 PM UTC (2a7e355)">Preview</a> | <a href="https://whatpr.org/fetch/1248/43a0c94...2a7e355.html" title="Last updated on Jun 3, 2021, 1:57 PM UTC (2a7e355)">Diff</a>

Set final connection timing info after failure check

---

fetch.bs

This regressed in 987c3fd3def02b630cce174cc33b827e64203b19.
Fixes #1249.
***
<a href="https://whatpr.org/fetch/1255.html" title="Last updated on Jun 17, 2021, 4:21 PM UTC (055acb9)">Preview</a> | <a href="https://whatpr.org/fetch/1255/acef461...055acb9.html" title="Last updated on Jun 17, 2021, 4:21 PM UTC (055acb9)">Diff</a>

Create AbortSignal earlier in new Request()

---

fetch.bs

* …
* …
* …
* Chrome: …
* Firefox: …
* Safari: …
***
<a href="https://whatpr.org/fetch/1290.html" title="Last updated on Aug 31, 2021, 1:12 PM UTC (7e53dfe)">Preview</a> | <a href="https://whatpr.org/fetch/1290/613aad9...7e53dfe.html" title="Last updated on Aug 31, 2021, 1:12 PM UTC (7e53dfe)">Diff</a>

minor fixes

---

fetch.bs

I noticed in https://github.com/whatwg/storage/issues/137 that the current setup is slightly bogus.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 3, 2022, 2:06 PM UTC)_.
<details>
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fwhatwg%2Ffetch%2F8ebf2fd5f700b8a23a8fb4697c3a6a213beb77b7%2Ffetch.bs&force=1&md-status=LS-PR&md-Text-Macro=PR-NUMBER%201407)
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> …
```

Support obtaining a network partition key from an environment

---

fetch.bs

See https://github.com/whatwg/url/issues/693 for context.
@mikewest want to review?
***
<a href="https://whatpr.org/fetch/1431.html" title="Last updated on May 2, 2022, 12:30 PM UTC (2519d68)">Preview</a> | <a href="https://whatpr.org/fetch/1431/14898c0...2519d68.html" title="Last updated on May 2, 2022, 12:30 PM UTC (2519d68)">Diff</a>

Account for localhost. (with trailing dot) in origin resolving

---

fetch.bs

Closes #1476 and closes #1477.
---
Thanks @jub0bs! Hope this looks good.
***
<a href="https://whatpr.org/fetch/1490.html" title="Last updated on Sep 22, 2022, 9:59 AM UTC (aac0fc6)">Preview</a> | <a href="https://whatpr.org/fetch/1490/0d95632...aac0fc6.html" title="Last updated on Sep 22, 2022, 9:59 AM UTC (aac0fc6)">Diff</a>

Editorial: correct some minor wording issues

---

fetch.bs

***
<a href="https://whatpr.org/fetch/1500.html" title="Last updated on Oct 7, 2022, 7:06 AM UTC (3cd0aea)">Preview</a> | <a href="https://whatpr.org/fetch/1500/c9039b9...3cd0aea.html" title="Last updated on Oct 7, 2022, 7:06 AM UTC (3cd0aea)">Diff</a>

Add "webidentity" to RequestDestination enum too

---

fetch.bs

***
<a href="https://whatpr.org/fetch/1498.html" title="Last updated on Oct 5, 2022, 3:53 AM UTC (7c8c508)">Preview</a> | <a href="https://whatpr.org/fetch/1498/1fbc40c...7c8c508.html" title="Last updated on Oct 5, 2022, 3:53 AM UTC (7c8c508)">Diff</a>

Explain the use-URL-credentials flag

---

fetch.bs

***
<a href="https://whatpr.org/fetch/1518.html" title="Last updated on Oct 26, 2022, 9:25 AM UTC (60ff9a0)">Preview</a> | <a href="https://whatpr.org/fetch/1518/8a241ca...60ff9a0.html" title="Last updated on Oct 26, 2022, 9:25 AM UTC (60ff9a0)">Diff</a>

Meta: my employer changed

---

fetch.bs

***
<a href="https://whatpr.org/fetch/1519.html" title="Last updated on Oct 26, 2022, 12:18 PM UTC (8940a4e)">Preview</a> | <a href="https://whatpr.org/fetch/1519/3ab48bf...8940a4e.html" title="Last updated on Oct 26, 2022, 12:18 PM UTC (8940a4e)">Diff</a>

Meta: slightly tweak employer and reformat

---

fetch.bs

***
<a href="https://whatpr.org/fetch/1521.html" title="Last updated on Oct 30, 2022, 1:09 PM UTC (b86acc6)">Preview</a> | <a href="https://whatpr.org/fetch/1521/9d17d81...b86acc6.html" title="Last updated on Oct 30, 2022, 1:09 PM UTC (b86acc6)">Diff</a>

Editorial: Fix a couple of typos

---

fetch.bs

Replacement for #1528, h/t @nico
***
<a href="https://whatpr.org/fetch/1529.html" title="Last updated on Nov 7, 2022, 10:49 AM UTC (512bcd6)">Preview</a> | <a href="https://whatpr.org/fetch/1529/154061f...512bcd6.html" title="Last updated on Nov 7, 2022, 10:49 AM UTC (512bcd6)">Diff</a>

Editorial: Remove a duplicate "in"

---

fetch.bs

And consistify callsite of no-CORS-safelisted request-header.
***
<a href="https://whatpr.org/fetch/1542.html" title="Last updated on Nov 21, 2022, 1:24 PM UTC (cc1a6a2)">Preview</a> | <a href="https://whatpr.org/fetch/1542/3cafbdf...cc1a6a2.html" title="Last updated on Nov 21, 2022, 1:24 PM UTC (cc1a6a2)">Diff</a>

Editorial: use tuple syntax

---

fetch.bs

***
<a href="https://whatpr.org/fetch/1546.html" title="Last updated on Nov 23, 2022, 4:52 PM UTC (4da4365)">Preview</a> | <a href="https://whatpr.org/fetch/1546/92e6c91...4da4365.html" title="Last updated on Nov 23, 2022, 4:52 PM UTC (4da4365)">Diff</a>

Editorial: minor nits, mainly around headers

---

fetch.bs

Fixes #1543.
***
<a href="https://whatpr.org/fetch/1545.html" title="Last updated on Nov 23, 2022, 4:03 PM UTC (96a39f5)">Preview</a> | <a href="https://whatpr.org/fetch/1545/92e6c91...96a39f5.html" title="Last updated on Nov 23, 2022, 4:03 PM UTC (96a39f5)">Diff</a>

Editorial: share validation logic in the Headers class

---

fetch.bs

***
<a href="https://whatpr.org/fetch/1548.html" title="Last updated on Nov 25, 2022, 5:07 PM UTC (4dfcd94)">Preview</a> | <a href="https://whatpr.org/fetch/1548/223ca89...4dfcd94.html" title="Last updated on Nov 25, 2022, 5:07 PM UTC (4dfcd94)">Diff</a>

Editorial: rely more on Infra in the data: URL processor

---

fetch.bs

Helps with #1526
***
<a href="https://whatpr.org/fetch/1554.html" title="Last updated on Dec 1, 2022, 3:14 AM UTC (fcac1a3)">Preview</a> | <a href="https://whatpr.org/fetch/1554/62e5d0b...fcac1a3.html" title="Last updated on Dec 1, 2022, 3:14 AM UTC (fcac1a3)">Diff</a>

Editorial: <div algorithm> wrappers for some definitions.

---

fetch.bs

Related to #1526
* …
* …
* …
* Chromium: …
* Gecko: …
* WebKit: …
***
<a href="https://whatpr.org/fetch/1565.html" title="Last updated on Dec 12, 2022, 9:47 AM UTC (b6571b7)">Preview</a> | <a href="https://whatpr.org/fetch/1565/f6e9b8d...b6571b7.html" title="Last updated on Dec 12, 2022, 9:47 AM UTC (b6571b7)">Diff</a>

Editorial: Add add more <div algorithm> wrappers

---

fetch.bs

- Add `<div algorithm>` wrappers to more algorithms=
- Fix definitions in obtain a connection
***
<a href="https://whatpr.org/fetch/1570.html" title="Last updated on Dec 14, 2022, 2:26 AM UTC (77f0bc7)">Preview</a> | <a href="https://whatpr.org/fetch/1570/bec03e6...77f0bc7.html" title="Last updated on Dec 14, 2022, 2:26 AM UTC (77f0bc7)">Diff</a>

Editorial: more nits and more <div algorithm> wrappers

---

fetch.bs

Add more <div algorithm> wrappers to algorithms definied in the Infrastructure section.
Related to: #1526
* …
* …
* …
* Chromium: …
* Gecko: …
* WebKit: …
***
<a href="https://whatpr.org/fetch/1573.html" title="Last updated on Dec 17, 2022, 6:38 PM UTC (759b0ea)">Preview</a> | <a href="https://whatpr.org/fetch/1573/06a38bc...759b0ea.html" title="Last updated on Dec 17, 2022, 6:38 PM UTC (759b0ea)">Diff</a>

Editorial: Add <div algorithm> to Infrastructure algs

---

fetch.bs

Related to: #1580
***
<a href="https://whatpr.org/fetch/1581.html" title="Last updated on Jan 2, 2023, 6:54 PM UTC (88c8ca2)">Preview</a> | <a href="https://whatpr.org/fetch/1581/464326e...88c8ca2.html" title="Last updated on Jan 2, 2023, 6:54 PM UTC (88c8ca2)">Diff</a>

Editorial: Fix implementation-defined links

---

fetch.bs

Related to #1526
***
<a href="https://whatpr.org/fetch/1582.html" title="Last updated on Dec 29, 2022, 10:21 PM UTC (b25db8e)">Preview</a> | <a href="https://whatpr.org/fetch/1582/464326e...b25db8e.html" title="Last updated on Dec 29, 2022, 10:21 PM UTC (b25db8e)">Diff</a>

Editorial: add <div algorithm> to HTTP extensions

---

fetch.bs

Also remove the no-backref class throughout as it's meaningless.
***
<a href="https://whatpr.org/fetch/1586.html" title="Last updated on Jan 3, 2023, 9:38 AM UTC (9fc1e0c)">Preview</a> | <a href="https://whatpr.org/fetch/1586/0332175...9fc1e0c.html" title="Last updated on Jan 3, 2023, 9:38 AM UTC (9fc1e0c)">Diff</a>

Editorial: correct keepalive note

---

fetch.bs

Start adding <div algorithm> tags to Fetching section.
Related To: #1526
***
<a href="https://whatpr.org/fetch/1591.html" title="Last updated on Jan 13, 2023, 10:19 AM UTC (fdc29cd)">Preview</a> | <a href="https://whatpr.org/fetch/1591/4500d3a...fdc29cd.html" title="Last updated on Jan 13, 2023, 10:19 AM UTC (fdc29cd)">Diff</a>

Editorial: Add <div algorithm> tags to fetch

---

fetch.bs

***
<a href="https://whatpr.org/fetch/1608.html" title="Last updated on Feb 20, 2023, 5:09 PM UTC (1a3c778)">Preview</a> | <a href="https://whatpr.org/fetch/1608/dc0f9e7...1a3c778.html" title="Last updated on Feb 20, 2023, 5:09 PM UTC (1a3c778)">Diff</a>

Exporting terms for service worker spec

---

fetch.bs

Related to: #1526.
***
<a href="https://whatpr.org/fetch/1612.html" title="Last updated on Mar 3, 2023, 3:02 AM UTC (c830647)">Preview</a> | <a href="https://whatpr.org/fetch/1612/cbfb5aa...c830647.html" title="Last updated on Mar 3, 2023, 3:02 AM UTC (c830647)">Diff</a>

Editorial: add <div algorithm> wrappers to Request class

---

fetch.bs

Related to: #1526.
***
<a href="https://whatpr.org/fetch/1616.html" title="Last updated on Mar 6, 2023, 10:56 PM UTC (723a903)">Preview</a> | <a href="https://whatpr.org/fetch/1616/0d897b8...723a903.html" title="Last updated on Mar 6, 2023, 10:56 PM UTC (723a903)">Diff</a>

Editorial: add <div algorithm> wrappers to section 5.

---

fetch.bs

Related to: #1526
***
<a href="https://whatpr.org/fetch/1619.html" title="Last updated on Mar 22, 2023, 3:23 PM UTC (7c2c7c5)">Preview</a> | <a href="https://whatpr.org/fetch/1619/2c08515...7c2c7c5.html" title="Last updated on Mar 22, 2023, 3:23 PM UTC (7c2c7c5)">Diff</a>

Editorial: add <div algorithm> wrappers to data URLs

---

fetch.bs

Fixes #1603.
cc @Ms2ger
***
<a href="https://whatpr.org/fetch/1649.html" title="Last updated on May 8, 2023, 7:05 AM UTC (ec3956f)">Preview</a> | <a href="https://whatpr.org/fetch/1649/4502481...ec3956f.html" title="Last updated on May 8, 2023, 7:05 AM UTC (ec3956f)">Diff</a>

Use the current realm for Response's static methods

---

fetch.bs

Also clean up an earlier internalResponse initialization.
cc @abinpaul1
***
<a href="https://whatpr.org/fetch/1653.html" title="Last updated on May 8, 2023, 9:40 AM UTC (07d7f13)">Preview</a> | <a href="https://whatpr.org/fetch/1653/5629d15...07d7f13.html" title="Last updated on May 8, 2023, 9:40 AM UTC (07d7f13)">Diff</a>

Editorial: share a conditional in fetch response handover

---

fetch.bs

Fixes #1676.
***
<a href="https://whatpr.org/fetch/1677.html" title="Last updated on Jun 23, 2023, 1:29 PM UTC (55c831d)">Preview</a> | <a href="https://whatpr.org/fetch/1677/0291bf1...55c831d.html" title="Last updated on Jun 23, 2023, 1:29 PM UTC (55c831d)">Diff</a>

Editorial: Fix typo

---

fetch.bs

Tests: https://github.com/web-platform-tests/wpt/pull/45350.
Fixes #1663.
* Chromium
* Gecko
* WebKit
* See above.
* Chromium: https://issues.chromium.org/issues/332391867
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1889059
* WebKit: N/A
***
<a href="https://whatpr.org/fetch/1743.html" title="Last updated on Apr 2, 2024, 9:05 AM UTC (3238092)">Preview</a> | <a href="https://whatpr.org/fetch/1743/76102d5...3238092.html" title="Last updated on Apr 2, 2024, 9:05 AM UTC (3238092)">Diff</a>

Block ports 4190 & 6679

---

.github/workflows/build.yml
PULL_REQUEST_TEMPLATE.md
fetch.bs

Also pull in some recent whatwg/spec-factory changes while here.
Closes #1772.
***
<a href="https://whatpr.org/fetch/1775.html" title="Last updated on Sep 20, 2024, 4:29 PM UTC (774bf26)">Preview</a> | <a href="https://whatpr.org/fetch/1775/3153e5e...774bf26.html" title="Last updated on Sep 20, 2024, 4:29 PM UTC (774bf26)">Diff</a>

Meta: link Simplified Chinese translation

---

fetch.bs

***
<a href="https://whatpr.org/fetch/1846.html" title="Last updated on Aug 12, 2025, 1:12 PM UTC (4dd730c)">Preview</a> | <a href="https://whatpr.org/fetch/1846/6738573...4dd730c.html" title="Last updated on Aug 12, 2025, 1:12 PM UTC (4dd730c)">Diff</a>

Meta: link to Korean translations
